### ISSUE TITLE
Tutorial / Documentation

### ISSUE THREAD

**Issue by nxhoaf** [jcodec/jcodec#1]
Hi, 

I'm looking for some ways to encode/decode .H264 file in java. After googling, I find out your project and very interested in it. Therefore, I couldn't figure out how to get started with it. 

So, can you please give me some documentations/tutorials or references ? 

Thank you.

**Comment by josesanpedro** [comment]
hi there Jay!

i recently found your library and i want to use it on my java projects. but i havent found any example that shows how to analise mxf videos with it.

can you give me a hand here? i need to export the embedded timecodes on the mxf timecode track. you think i can do that with jcodec?

thanks in advance.

**Comment by rabiaPucit** [comment]
I want to download jcodec for android from jcode.org. I tried a lot to download android-0.1.7 zip file from there but everytime it says that web page not available. Then i got it from github from the link i.e https://github.com/jcodec/jcodec. But i am unable to import it in android eclipse. I simply want to use jcodec in my android project for making video from images. How to download jcodec and import its package in my eclipse? Any help in this regard?

**Comment by dkonstantinov** [comment]
Hello, JCodec Team,

Could You please tell me, is it possible to convert video into videos of different resolutions (240p, 360p, 480p, 720p, 1080p) with the help of jcodec library ?

**Comment by jcodec** [comment]
Yes, it is possible, but the output size will be large.

Jay

**Comment by autarchictechie** [comment]
hi there,

I am a computer science student and working on MPEG 1 encryption. I am doing a selective encryption on sign bits of motion vector of macro block. But i am not able to find how to parse MPEG bitstream to get this sign bit, please help me. I am working from months on this but couldn't find anything, I guess it can be done using your MPEG decoder. Please help....

**Comment by svitvitskiy** [comment]
That's the line you need:

https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/codecs/mpeg12/MPEGPred.java#L408

And here's how you can see it in action

git clone https://github.com/jcodec/jcodec.git
cd jcodec
mvn clean install; cd javase; mvn clean install; cd ../samples; mvn clean
install; cd ..
java -cp
"target/jcodec-0.2.0.jar:javase/target/jcodec-javase-0.2.0.jar:samples/target/jcodec-samples-0.2.0.jar"
org.jcodec.samples.transcode.TranscodeMain mpeg2img <your file>.mpg
/tmp/frame_%08d.jpg

Stan

**Comment by MLS-ICP** [comment]
Hi,
I find this library very useful and having huge potentials. Recently, I have been trying to apply H264 codec to a video files but I could not manage to get it done. Could you please help me how can I apply the codec to a raw video file.
Thanks in advance,
H

**Comment by toriqultonu** [comment]
how can I learn jcodec to make a project that converts arrays of images into video file??? plz help me anyone...!

**Comment by zhuker** [comment]
> how can I learn jcodec to make a project that converts arrays of images into video file??? plz help me anyone...!

@toriqultonu 
## H264 video from png images
```
File output = new File("test.mp4");
SequenceEncoder enc = SequenceEncoder.createWithFps(NIOUtils.writableChannel(output), new Rational(1, 1));
String[] files = {"frame0.png", "frame1.png", "frame2.png"};
for (String file : files) {
   enc.encodeNativeFrame(AWTUtil.decodePNG(new File(file), ColorSpace.RGB));
}
enc.finish();
```
