### ISSUE TITLE
How to change intervals between slides?

### ISSUE THREAD

**Issue by categola** [jcodec/jcodec#100]
Hi, I use JCodec to create video from some images.
I could set interval seconds between slides by MP4Packet parameter.
But can I change interval in one movie ?
For example, 1 sec between first image and second slide, 2 sec between second slide and third slide.
Actually I tried and generated mp4 file, but movie player did not work as I expected.
Please let me know if the above is possible.
Thanks.

**Comment by JeetChaudhary** [comment]
Hey bro, Can you please tell me how to create video using multiple images..? Please help me out..

**Comment by svitvitskiy** [comment]
The answer is Yes and No.

MP4 container supports individual duration for each frame meaning you can
have a frame that lasts for two seconds followed by a frame that lasts half
a second etc.

Low level APIs in JCodec allow you to specify the duration of a packet (
https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/TranscodeMain.java
in method prores2avc uses low level API ).

However SequenceEncoder class which most people use ( a high level API )
doesn't expose that option.

I need to think about the best way to expose this functionality without
complicating the high level API, meanwhile you can resort to low level API
and use the TransocderMain (see above) as a sample.

Stan

**Comment by categola** [comment]
Thanks for your reply.
I will check and try low level API according to TranscodeMain.java.
Maybe in Xmas holidays. :-)

**Comment by categola** [comment]
I learned how to create video in the following thread.
https://github.com/jcodec/jcodec/issues/64
I hope this will help you.
