### ISSUE TITLE
Parameters in outTrack.addFrame and addSampleEntry

### ISSUE THREAD

**Issue by jeetdholakia** [jcodec/jcodec#104]
Hey guys,

I'm writing a code with merges images into video. And so far I've managed to achieve it, but the video generated moves the images so fast I cant even see them. 

Im aware I can slow the framerate down by outTrack.addFrame parameters , but I dont know which one to change. Please help me out.

Currently my params are : 

`outTrack.addFrame(new MP4Packet(result, i, timescale, 5, i, true, null, i, 0));`

What params do I need to tune? I want a frame to stay about half a second. 

Also, what does the last parameter mean in the following method?

 `outTrack.addSampleEntry(H264Utils.createMOVSampleEntry(spsList,ppsList,4));`

Thanks,
Jeet

**Comment by svitvitskiy** [comment]
The parameters that control presentation of frames are duration and
timescale. Duration tells for how many time units the frame should be
presented and timescale specifies how many time units there are in a second.

For example with timescale = 30 a duration of 15 means half a second, while
duration 60 means 2 seconds.

The last parameter to H264UtilscreateMOVSampleEntry constructor means how
many bytes to use for NAL unit length field, unfortunately MP4 gives you a
chose so does JCodec. The most common value is 4.

Stan
