### ISSUE TITLE
Odd artifacts in some exported MP4s?

### ISSUE THREAD

**Issue by rdamiano** [jcodec/jcodec#114]
I have an app that allows users to create animations, it uses jcodec to export the animations as MP4.

Many users upload their animations to Youtube, and they look fine. Others have animations that have odd artifacts like this: https://www.youtube.com/watch?v=eycOo2pfBYc

It seems to only happen with colored backgrounds, but not exclusively - and not all the time. I've found out in one case that a user exported their MP4 at a 640x360 resolution on a Galaxy S4 phone and they experienced the same artifacts.

I'm not sure if there's something I can do to prevent this? My actual jcodec code is taken from [SequenceEncoder.java](https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/api/SequenceEncoder.java).

---

**Here's how I set things up:**

```
// Muxer that will store the encoded frames.
_mp4Muxer = mp4Muxer;

// Add a video track to the muxer.
_fps = fps;
_outTrack = _mp4Muxer.addTrack(TrackType.VIDEO, _fps);

// Allocate a buffer big enough to hold output frames.
_encodedByteBuffer = ByteBuffer.allocate(exportWidth * exportHeight * 3);

// Create an instance of an encoder.
_encoder = new H264Encoder(new H264FixedRateControl(512)); // Was 256, apparently 512 is much better quality.

// Transform to convert between RGB and YUV.
_transform = ColorUtil.getTransform8Bit(ColorSpace.RGB, _encoder.getSupportedColorSpaces()[0]);

// Extra data of encoder (SPS, PPS) to be stored in a special place of MP4.
_spsList = new ArrayList<ByteBuffer>();
_ppsList = new ArrayList<ByteBuffer>();

// Picture that will hold pixels and be encoded.
_pictureRGB = Picture8Bit.create(exportWidth, exportHeight, ColorSpace.RGB);
_pictureToEncode = Picture8Bit.create(exportWidth, exportHeight, _encoder.getSupportedColorSpaces()[0]);

// Start this Thread.
_lockObject = new Object();
start();
```

**And here's the encoding part, it's inside the run() function of a Thread and receives new rgba pixels constantly until encoding is done:**

```
@Override
public void run()
{
	// Runs until dispose() is called.
	while (_isAlive == true)
	{
		// Don't do any of this if finish() or cancel() was already called.
		if (_isFinishedEncoding == false && _isCancelled == false)
		{
			synchronized (_lockObject)
			{
				// If _rgbaPixels isn't null, encode the pixels.	
				if (_rgbaPixels != null)
				{
					// Put pixels into an RGB picture.
					byte[] dstData = _pictureRGB.getPlaneData(0);
					
					int offset = 0;
					for (int k = 0, length = dstData.length; k < length; k += 3)
					{
						dstData[k] = (byte)(_rgbaPixels[offset++] - 128);
						dstData[k + 1] = (byte)(_rgbaPixels[offset++] - 128);
						dstData[k + 2] = (byte)(_rgbaPixels[offset++] - 128);
						offset++;
					}							
					
					// Perform conversion.
					_transform.transform(_pictureRGB, _pictureToEncode);
					
					// Encode image into H.264 frame, the result is stored in _encodedByteBuffer.
					_encodedByteBuffer.clear();
					ByteBuffer result = _encoder.encodeFrame(_pictureToEncode, _encodedByteBuffer);
					
					// Based on the frame above, form the correct MP4 packet.
					_spsList.clear();
					_ppsList.clear();
					H264Utils.wipePS(_encodedByteBuffer, _spsList, _ppsList);
					H264Utils.encodeMOVPacket(result);
					
					// We presume there will be only one SPS/PPS pair for now
					if (_sps == null && _spsList.size() != 0)
						_sps = _spsList.get(0);
					if (_pps == null && _ppsList.size() != 0)
						_pps = _ppsList.get(0);
					
					try
					{
						_outTrack.addFrame(new MP4Packet(result, _encodedFrameIndex, _fps, 1, _encodedFrameIndex, false, null, _encodedFrameIndex, 0));
					}
					catch (IOException e)
					{}
					
					_encodedFrameIndex++;
					
					// Prepare for more pixels.
					_rgbaPixels = null;
					_isReadyForMorePixels = true;
					_isProcessingPixels = false;
				}
			}
		}
	}
	
	// Can only be reached after dispose() is called.
	_transform = null;
	_outTrack = null;
	_encoder = null;
	_mp4Muxer = null;
	_pictureRGB = null;
	_pictureToEncode = null;
	_encodedByteBuffer = null;
	_spsList = null;
	_ppsList = null;
	_rgbaPixels = null;
	_lockObject = null;
}
```

---

Wondering if this is something I can fix on my end, or perhaps an issue within the jcodec library?

**Comment by svitvitskiy** [comment]
Thanks, I will look.

Stan

**Comment by rdamiano** [comment]
Thanks. Just want to let you know that I was just able to recreate this on my end on my PC, so I don't believe it's related to mobile device/platform-dependent. I can't tell exactly why it happens only sometimes, it seems to have to do with more than just a few colors being on the screen, or maybe only bright/neon-like colors?

I've attached a ZIP that has [5 small MP4 files in it](http://i.imgur.com/gDdQG0Z.png). Four of them are all the same animation but with a different background color, showing off the different artifact patterns. Then there's one different MP4 file that has no artifacting at all. Not sure if looking at these files will help you.

[Export Artifacts.zip](https://github.com/jcodec/jcodec/files/116421/Export.Artifacts.zip)

---

**Also, the only thing I didn't copy from SequenceEncoder.java is this part:**

NALUnit nu = NALUnit.read(NIOUtils.from(result.duplicate(), 4));
// ...
// Add packet to video track
outTrack.addFrame(new MP4Packet(result, frameNo, 25, 1, frameNo, nu.type == NALUnitType.IDR_SLICE, null, frameNo, 0));

I just always pass in "false" since `NalUnit nu` was always not equal to `NALUnitType.IDR_SLICE`, not sure if this has anything to do with anything though.

**Comment by svitvitskiy** [comment]
Than you! Could you attach source images or raw video so I can reproduce
locally?

Stan

**Comment by rdamiano** [comment]
Sure. Though, in my code, I grab RGBA pixels through OpenGL and pass that into jcodec, rather than images. Not sure if that matters. If it does, I suppose I can export RGBA frame data to a TXT file and give you the appropriate code to read the pixels from it.

However, for now, I've exported the animation as a GIF and saved each frame as a PNG, attached is the ZIP. Hope this doesn't prevent you from recreating this.

[Artifact Test.zip](https://github.com/jcodec/jcodec/files/117473/Artifact.Test.zip)

**Comment by svitvitskiy** [comment]
Thanks, I was able to reproduce it locally, debugging...

**Comment by svitvitskiy** [comment]
Fixed

**Comment by rdamiano** [comment]
Wow that's great, can't believe it's seemingly such a simple fix too. Thanks for looking into it so quickly!
