### ISSUE TITLE
MPSUtils.parseDescriptors() can cause a BufferUnderflowException

### ISSUE THREAD

**Issue by jrnorth** [jcodec/jcodec#118]
In [`MPSUtils.parseDescriptors()`](https://github.com/jcodec/jcodec/blob/69ca28b1925a828cbec73d8c7d12fb3cc0d6f625/src/main/java/org/jcodec/containers/mps/MPSUtils.java#L367), each descriptor's tag and length are parsed, and then a `ByteBuffer` containing only the descriptor's data is passed to the new `MPEGMediaDescriptor`'s `parse()` method. However, `MPEGMediaDescriptor`'s `parse()` method attempts to parse the tag and length, which are no longer there. This can cause a `BufferUnderflowException`. A potential solution is to use `ByteBuffer`'s absolute [`get(int)`](http://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#get(int)) method in `parseDescriptors()` so the tag and length aren't consumed and can be safely parsed by the `MPEGMediaDescriptor`: https://gist.github.com/jrnorth/d5fc4ea2ef9445fca1a8.

**Comment by svitvitskiy** [comment]
Thanks for looking, let me have a look.

Stan

**Comment by svitvitskiy** [comment]
Fixed in b54c5b282d14bd87e0deca736a033183a2d36e1d
