### ISSUE TITLE
MPSUtils.parseDescriptors() doesn't return any descriptors

### ISSUE THREAD

**Issue by jrnorth** [jcodec/jcodec#119]
In [`MPSUtils.parseDescriptors()`](https://github.com/jcodec/jcodec/blob/69ca28b1925a828cbec73d8c7d12fb3cc0d6f625/src/main/java/org/jcodec/containers/mps/MPSUtils.java#L365), a `List` to hold the returned descriptors is created but is never added to. Therefore, every time this method is called, the caller will get an empty `List`.

**Comment by svitvitskiy** [comment]
Fixed in b54c5b282d14bd87e0deca736a033183a2d36e1d

**Comment by svitvitskiy** [comment]
If you want more descriptors in there, feel free to send a pull request. For reference: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mpegts.c
function 'ff_parse_mpeg2_descriptor'
