### ISSUE TITLE
Failed to resolve: org.jcodec:jcodec-android:0.2.0

### ISSUE THREAD

**Issue by ghost** [jcodec/jcodec#125]
i want to use jcodec version 0.2.0 to use Frame grab and bitmapwithmetadata 
but this api  didn't install

**Comment by kolipass** [comment]
Try this:

1.  go to your jcodec folder from CL;

2.  mvn clean install

2.  cd android/

3.  mvn clean install

**Comment by zhuker** [comment]
https://mvnrepository.com/artifact/org.jcodec/jcodec/0.2.0
