### ISSUE TITLE
Get total number of frames or duration of a video?

### ISSUE THREAD

**Issue by mongoose54** [jcodec/jcodec#126]
Is there a method that returns the duration or total number of frames in a video?

**Comment by mongoose54** [comment]
Just found the solution:

``
	        ch = NIOUtils.readableFileChannel(new File(filePath));
		    MP4Demuxer demuxer = new MP4Demuxer(ch);
		    DemuxerTrack video_track = demuxer.getVideoTrack();
		    log.info("video_duration: "+ video_track.getMeta().getTotalDuration());
``

**Comment by KonstantineVashalomidze** [comment]
@mongoose54 Little late but MP4Demuxer constructor is not public how did you manage to construct the object out of it? 

edit: It appears there is static factory method for creating object like this: ```MP4Demuxer.createMP4Demuxer(ch)```

**Comment by himslm01** [comment]
>             DemuxerTrack video_track = demuxer.getVideoTrack();
>             log.info("video_duration: "+ video_track.getMeta().getTotalDuration());
> `

Does the total duration include frames which are to be excluded from playback by edit lists, for instance in .mov?
