### ISSUE TITLE
Compilation issues while trying to build samples

### ISSUE THREAD

**Issue by gaurav-lagad** [jcodec/jcodec#143]
Hi,
I am trying to build samples project using mvn install but I get the following error:
`Failed to execute goal on project jcodec-samples: Could not resolve dependencies for project org.jcodec:jcodec-samples:jar:0.2.0: Could not find artifact org.jcodec:jcodec-javase:jar:0.2.0 in gson (http://google-gson.googlecode.com/svn/mavenrepo)`

I checked the available version for "jcodec-javase" on the central repository but the latest version available seems to be 0.1.9 and not 0.2.0. Can you please check with this discrepancy ? 
Thanks!

**Comment by zhuker** [comment]
should be good now
