### ISSUE TITLE
Is svitvitskiy alive?

### ISSUE THREAD

**Issue by clocksmith** [jcodec/jcodec#147]
Nothing has been updated in 6 months. Is anyone maintaining this?

**Comment by zhuker** [comment]
@clocksmith i am working on it in a branch called "vg"

**Comment by svitvitskiy** [comment]
Hey, yes, I am alive :) What can I help you with?

**Comment by davidwin3** [comment]
@svitvitskiy Please publish to maven version 0.2.0. 😆 
Thank you very much.

**Comment by mufumbo** [comment]
hum, is this going to happen? how are you guys working without maven?

**Comment by zhuker** [comment]
https://mvnrepository.com/artifact/org.jcodec/jcodec/0.2.0
