### ISSUE TITLE
H264 Decoder output has wrong frame size

### ISSUE THREAD

**Issue by chjcken** [jcodec/jcodec#154]
Hi there,

I have an h264 i-frame - it's original size is 360x640
I tried to decode it with H264Decoder but the output size is 368x640
code I use here:
```
H264Decoder h264Decoder = new H264Decoder();  

Picture buffer = Frame.create(1920, 1920, ColorSpace.YUV420);
Frame decodedFrameMeta = h264Decoder.decodeFrame(h264Frame, buffer.getData());

System.out.println(decodedFrameMeta.getWidth() + "x" + decodedFrameMeta.getHeight());
```

I tried to decode this frame using OpenH264 decoder (c++) and output size is 360x640 and the video contains this frame is also 360x640

then I tried to decode using Broadway decoder (javascript) and output size is wrong like java codec too, 368x640

Can you guy explain me if this is a real issue or my frame size just has wrong size from the beginning

Unfortunately, I lost the video contains the frame, only frame is kept (see attachment).
Hope you take a look. Thank you
[h264frame.zip](https://github.com/jcodec/jcodec/files/568174/h264frame.zip)

**Comment by RogerHardiman** [comment]
The H264 compression algorithms require all video widths and heights to be multiples of 16.
So to encode your original image (360x640) has to be placed in a larger frame (368x640) for compression.

In the SPS and PPS data that go with the video the H264 spec then defines a cropping area so the decoder knows to take the 368x640 and crop out the slightly smaller 360x640 rectangle.

So in this case the decodedFrame width and height (368 and 640) are both correct.
You need to be looking in the SPS/PPS data for the cropping information and applying your own cropping.

Some H264 decoders so this automatically for you making it seamless so I assume OpenH264 does the cropping for you.

**Comment by chjcken** [comment]
thank you for the clear explanation

i'm closing this issue now
