### ISSUE TITLE
Maven binaries jcodec-javase:0.1.9 seems to fail to link

### ISSUE THREAD

**Issue by beefeather** [jcodec/jcodec#160]
**jcodec-javase:0.1.9 is incompatible with jcodec-0.1.9**.

I tried a first sample named "Get a single frame" in my IDEA IDE.
I added a maven dependency "org.jcodec:jcodec-javase:0.1.9" asking IDE to arrange it for me.

There was an exception:
`Exception in thread "main" java.lang.NoSuchMethodError: org.jcodec.common.NIOUtils.closeQuietly(Ljava/io/Closeable;)V
	at org.jcodec.api.awt.FrameGrab.getFrame(FrameGrab.java:102)`

Indeed, the method NIOUtils.closeQuietly (from jcodec-0.1.9) lacks the required signature. Instead, according to reflection, it's only overloaded for ReadableByteChannel and RandomAccessFile parameters.

**Comment by beefeather** [comment]
Just copying FrameGrab.getFrame from the library to my code helps (since it gets properly recompiled for new method signatures).

**Comment by zhuker** [comment]
use 0.2.0 - should be good
