### ISSUE TITLE
JCodec MIGHT be usable (working on it)

### ISSUE THREAD

**Issue by stefan-reich** [jcodec/jcodec#163]
JCodec is just not usable, is it? Basic stuff doesn't work. Samples on http://jcodec.org are not even compilable.

I guess for reading videos JCodec might work. But I also need a way to make videos from Java.

Any ideas?

**Comment by svitvitskiy** [comment]
Please post the specific samples that don't work for you and describe the
intended begavior.

Stan

**Comment by stefan-reich** [comment]
Ah. Well... I want to make a video from a stream of BufferedImages and in-memory raw PCM data.

Also I think I used an earlier version of JCodec before... I just downloaded the latest version from GitHub and ran Maven on it, is that the right way?

Thanks!

**Comment by stefan-reich** [comment]
Oh... I'm finding stuff. [This](https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/gen/SequenceEncoderDemo.java) is the sample I want I guess. You might want to update the code lines on the home page as it is different from the actual sample program.

**Comment by svitvitskiy** [comment]
Yeah, different parts are lagging behind, doing the best I can at the
moment :)

In case you run into problems please post them so that I can fix.

Thanks.

Stan
