### ISSUE TITLE
Add sound to video

### ISSUE THREAD

**Issue by stefan-reich** [jcodec/jcodec#164]
Hi, please advise how I can add sound to a video? I want to encode from a raw PCM stream. Here is my (Stan's) [demo program](http://tinybrain.de/1006716) that makes the video without sound.

OK, I heard AAC encoding is not supported in Java? Can I encode to something else (ogg maybe)?

**Comment by svitvitskiy** [comment]
You might want to consider using [Transcoder](https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/Transcoder.java) class. This class sits in samples but it will be moved to the main project as soon as I finish implementing PNG encoder/decoder. The class is a high-level transcoder interface that you can 'just' give your files and it will figure out.

For the example of usage look at [TranscodeMain](https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/TranscodeMain.java) class. Ideally you should be able to run TranscodeMain like this:
```
java -cp jcodec-<version>.jar:jcodec-javase-<version>.jar:jcodec-samples-<version>.jar org.jcodec.samples.transcode.TranscodeMain --o:ac=copy <your input file.wav> <your output file.mp4>
```
The command above will copy PCM audio from your input file wav file to your output MP4 file.

Unfortunately right now JCodec doesn't have an AAC encoder (nor any other audio encoder). So encoding raw PCM audio is not possible.

If you are looking to mux audio from one file and video from another file into a single destination file let me know, this feature can be added in a reasonable time.

**Comment by stefan-reich** [comment]
Cool! Thank you very much :-)

**Comment by svitvitskiy** [comment]
You can again use [Transcoder](https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/Transcoder.java) class.

```
java -cp jcodec-<version>.jar:jcodec-javase-<version>.jar:jcodec-samples-<version>.jar org.jcodec.samples.transcode.TranscodeMain --o:ac=pcm <your input file.mp4> <your output file.wav>
```
The above will convert your AAC MP4 file into a WAV file (using AAC decoder).

Again, I apologize if you run into specific combination that's not working. Please post samples so I have a chance to look.

As far as audio is concerned JCodec only supports decoding AAC and encoding it into PCM (both WAV and MP4). It also supports copying AAC or PCM audio from input file to output file unaltered.

**Comment by stefan-reich** [comment]
Thank you very much, I will report!

**Comment by stefan-reich** [comment]
I'm still wondering about this line:

`TranscodeMain --o:ac=copy <your input file.wav> <your output file.mp4>`

That doesn't look correct.

**Comment by TimbresDev** [comment]
Same here, 

TranscodeMain --o:ac=copy test.wav test.mp4

==>>
[ERROR]	org.jcodec.common.JCodecUtil.createDemuxer (JCodecUtil.java:215):	Format WAV is not supported
Exception in thread "main" java.lang.NullPointerException
	at org.jcodec.api.transcode.TranscodeMain.main(TranscodeMain.java:256)

**Comment by TimbresDev** [comment]
> If you are looking to mux audio from one file and video from another file into a single destination file let me know, this feature can be added in a reasonable time.

Yes please, this would be a great feature: being able to specify an input WAV file that gets added as audio track to an existing MP4 file. Then we could use jcodec to create movies with sound.

**Comment by svitvitskiy** [comment]
Done. https://github.com/jcodec/jcodec/commit/4d83bb073226489d41f28893126c582a715fb3b0
