### ISSUE TITLE
Changing colors when encoding H264

### ISSUE THREAD

**Issue by mrieser** [jcodec/jcodec#173]
I'm trying to encode a series of PNG files to H264. I've attached one of the PNG files as a reference. ![img-00001](https://cloud.githubusercontent.com/assets/1038453/23569389/4e45cf90-005f-11e7-8eff-a0aa830462a9.png)

When I encode it to mp4/H.264, the dark-gray background becomes black. I tried to play around with different quality settings (e.g. using `new H264FixedRateControl(1024)` instead of `new DumbRateControl()`), but it didn't make a change.

When I encoded the same files to ProRes, the gray stayed gray (independent of the profile, I tried all four of them: HQ, STANDARD, LT, PROXY).
The following screenshot shows the two movies next to each other: ProRes on the left, H.264 on the right.

![screen shot](https://cloud.githubusercontent.com/assets/1038453/23569406/60516cf8-005f-11e7-8bab-c5136f6ccda3.png)

Encoding the same PNGs with FFMPEG to H264 does not change the gray to black, so the YUV420 color space should be able to handle those colors.

Can the color during encoding be controlled somehow in order to prevent such a color shift?

**Comment by svitvitskiy** [comment]
Yes, this is probably due to the difference between full range and studio range. Try modifying H264Encoder and have getSupportedColorSpaces return YUV420 instead of YUV420J and see if that helps.

**Comment by mrieser** [comment]
I changed YUV420J to YUV420 in two places in H264Encoder.java, but now I get the following Exception on the first frame I add: 
```
Exception in thread "Thread-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jcodec.codecs.h264.H264Utils.createAvcCFromPS(H264Utils.java:455)
	at org.jcodec.containers.mp4.muxer.FramesMP4MuxerTrack.setCodecPrivateIfNeeded(FramesMP4MuxerTrack.java:372)
	at org.jcodec.containers.mp4.muxer.FramesMP4MuxerTrack.finish(FramesMP4MuxerTrack.java:257)
	at org.jcodec.containers.mp4.muxer.MP4Muxer.finalizeHeader(MP4Muxer.java:141)
	at org.jcodec.containers.mp4.muxer.MP4Muxer.finish(MP4Muxer.java:122)

```

I think there is another exception somewhere, that results in `MP4Muxer.finish()` being called too early, but I haven't found yet the other exception. I'll keep digging through the code and will get back once I find something (or not). But thanks already for the pointer about the ColorSpace.

**Comment by mrieser** [comment]
Okay, got it working by modifying some more files (`CAVCL. codeTableChromaDC` did not yet handle the YUV420 case, and `EncodedMB` assumed YUV420J for its `pixels` member).

Is there interest in a PR to introduce an option to choose the color space for the H264-Encoder?

**Comment by xardazz** [comment]
mrieser, yep, pls go for PR, it's really good  when someone makes jcodec work much better

**Comment by mrieser** [comment]
See PR #174.
