### ISSUE TITLE
Create video from png image files

### ISSUE THREAD

**Issue by idoor88** [jcodec/jcodec#186]
Hi All, 
I tried a couple of ways to create a video from png image files with jcodec from googling, but all failed, some ways are from the old jcodec version, but the code is not even backward compatible, finally I tried the 0.2.0 version of the jcodec in the github with SequenceMuxer class as following:

                File file = new File("test.mp4");
		  SequenceMuxer smuxer = new SequenceMuxer(file);
		  
		  for(int ii=1; ii<6; ii++){
			  File imageFile = new File("image0"+ii+".png");
			  smuxer.encodeImage(imageFile);
		  }
		  smuxer.finish();

The video file test.mp4 is created, but no video player can even play it, It complained format is not supported.

I also tried this way:

 File out2 = new File("TestVideo.mp4");
	      
	        AWTSequenceEncoder8Bit enc2 = AWTSequenceEncoder8Bit.create2997Fps(out2); 
	       
	        for (int i = 0 ; i < 5 ; i++ ){

	           BufferedImage bi = ImageIO.read(new File("image0"+(i+1)+".png"));
	        
	           enc2.encodeImage(bi);
	        }
	        enc2.finish();

I got the video, and it can play, but only shows the first still image.
What have I done wrong? please help!! and thanks in advance.
Best Regards.

**Comment by svitvitskiy** [comment]
Hi, thank you for reporting. Some video players will behave weirdly with jcodec-encoded videos, I will need to look into that. However ffmpeg and vlc should be fine.

If you just need to encode a bunch of PNGs you can have a look at a [Transcoder](https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/api/transcode/Transcoder.java) class. The high-level example of usage is actually the [TranscodeMain](https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/api/transcode/TranscodeMain.java) class.

You are bringing up interesting issues in your report though, I'll look into this meanwhile.

**Comment by idoor88** [comment]
Hi, thanks very much for your response, I downloaded VLC and tested the two video files created from above code, it works, but it is very fast with 0 duration, also if I play with QuickTime, it does not work.
Also followed the TranscodeMain approach, and tested it, it worked as well even on quicktime, but also played very fast with 0 duration,  how do I control time/frame rate, and control when to play which image?

Thanks for your help.
