### ISSUE TITLE
InputStream as input instead of File

### ISSUE THREAD

**Issue by AmiroooTheWalnut** [jcodec/jcodec#193]
I have a problem for inputting a video into my code. The problem is that I only have an InputStream to the file (becasue it's crossplatform and I wanted to avoid pathing and privilege problems), I made a ReadableByteChannel from InputStream, however in the sources all ways finishes into FileChannelWrapper then to FileChannel. I made a handmade class for converting InputStream into SeekableByteChannel which gives below error and it's very poor made:
java.io.IOException: Could not find movie meta information box
    at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:60)
    at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:50)
    at org.jcodec.api.FrameGrab.<init>(FrameGrab.java:75)
    at org.jcodec.api.FrameGrab.getNativeFrame(FrameGrab.java:329)
    at mygame.MainGame.InitApp(MainGame.java:118)

Also I don't have any idea how to convert ReadableByteChannel into SeekableByteChannel, though SeekableByteChannel is extended from ReadableByteChannel. :( I'm noob.

Can you please help me to handle InputStream instead of a file? I couldn't find an example with an InputStream on the repository.

**Comment by svitvitskiy** [comment]
Unfortunately just an InputStream won't be enough to read from an MP4 file. MP4 files require random access as chunks of media data can be scattered across the file and don't have to follow in a sequential order. So in order to make an adequate wrapper you would need to have an input stream with a possibility of seeking. The only viable option is to construct a wrapper on top of RandomAccessFile class if that is better then channels.
Alternatively if you have some way to create an input stream to the resource at an offset (HTTP 1.1 Range header) you could implement a wrapper that will close the existing input stream every time the position(long) is called and reopen a new one at a specified offset.
If you let me know of your specific use case I might be able to help.

**Comment by AmiroooTheWalnut** [comment]
Thanks for your reply svitvitskiy. Seeking is not my priority, I want to make textures out of video and put it in LWJGL renderer. I didn't go deep into classes but as far as it can be seen from the classes like FrameGrab, I feel that it needs much revisions for what I'm going to do without the file itself. What I've done is something like this which gives that Exception:
```java
package mygame;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.channels.Channels;
import java.nio.channels.ClosedChannelException;
import java.nio.channels.ReadableByteChannel;
import org.jcodec.common.SeekableByteChannel;

public class VideoSBCH {

    SeekableByteChannel sbc = new SeekableByteChannel() {
        public int read(ByteBuffer dst) throws IOException {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            throwIfNotOpen();
            if (dst.remaining() > 0 && position == maxBytesToRead) {
                return -1;
            } else if (dst.remaining() > maxBytesToRead - position) {
                int oldLimit = dst.limit();
                dst.limit(dst.position() + maxBytesToRead - position);
                int numRead = readChannelDelegate.read(dst);
                dst.limit(oldLimit);
                position += numRead;
                return numRead;
            }
            int numRead = readChannelDelegate.read(dst);
            position += numRead;
            return numRead;
        }

        public int write(ByteBuffer src) throws IOException {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public long position() throws IOException {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            throwIfNotOpen();
            return position;
        }

        public SeekableByteChannel position(long newPosition) throws IOException {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            throwIfNotOpen();
            if ((newPosition != 0) && ((newPosition < 0) || (newPosition >= size()))) {
                throw new IllegalArgumentException(
                        String.format(
                        "Invalid seek offset: position value (%d) must be between 0 and %d",
                        newPosition, size()));
            }
            readStream.reset();
            readStream.skip(newPosition);
            position = (int) newPosition;
            return this;
        }

        public long size() throws IOException {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            throwIfNotOpen();
            return maxBytesToRead;
        }

        public SeekableByteChannel truncate(long size) throws IOException {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public boolean isOpen() {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            return readChannelDelegate.isOpen();
        }

        public void close() throws IOException {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            readChannelDelegate.close();
        }
    };
    private final InputStream readStream;
    private final int maxBytesToRead;
    private final ReadableByteChannel readChannelDelegate;
    // Internal accounting of position in the stream.
    private int position;

    public VideoSBCH(InputStream readStream, int maxBytesToRead) {

        this.readStream = readStream;
        this.maxBytesToRead = maxBytesToRead;

        // Seeking will be relative to the current position in the stream; 
        readStream.mark(this.maxBytesToRead);
        this.readChannelDelegate = Channels.newChannel(this.readStream);
        this.position = 0;
    }

    public boolean isOpen() {
        return readChannelDelegate.isOpen();
    }

    /**
     * Throws if this channel is not currently open.
     */
    private void throwIfNotOpen()
            throws IOException {
        if (!isOpen()) {
            throw new ClosedChannelException();
        }
    }
}
```
I'm sorry it's a little bit off-topic but maybe I can make a sequence of textures (marginally revised from image) in Desktop and then use it on other platforms because the Texture reader is reliable and cross-platform fits for OpenGL. And another solution is to make a temporary file and feed it into FrameGrab.  But I don't have idea about performance of them, I should test.
Do you think there is a way to use InputStream like the code I've wrote? or it needs to get more deep into the source?

**Comment by AmiroooTheWalnut** [comment]
A pure sequence of textures of a 60 seconds 640*640 24bit 3.4MB video got about 666MB and a 14 seconds 300*170 24bit 540KB video got about 11MB, seems to be heavily exponential! lol but extremely high performance for swapping frames. Thanks any way, I should learn much more.
