### ISSUE TITLE
NullPointerException in FrameGrab(SeekableByteChannel _in) constructor

### ISSUE THREAD

**Issue by karmakaze** [jcodec/jcodec#197]
```
        Format detectFormat = JCodecUtil.detectFormatBuffer(header);
        SeekableDemuxerTrack videoTrack = null;

        switch (detectFormat) {
```
The method `detectFormatBuffer` may return null which is dereferenced at the `switch` and throwing a NullPointerException before getting to the `default` case.

https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/api/FrameGrab.java#L82-L85

**Comment by svitvitskiy** [comment]
Fixing in PR #242
