### ISSUE TITLE
Where does jcodec get released?

### ISSUE THREAD

**Issue by Daxten** [jcodec/jcodec#202]
After some search I've found 0.2.0 only released here: https://bintray.com/mateuszlisik/maven/jcodec
 is this the official repo?

**Comment by svitvitskiy** [comment]
Maven central is wher it gets dropped however the 0.2.0 hasn't been released yet, I am working to fix a couple of bugs before I push it to central.

**Comment by zhuker** [comment]
released
https://mvnrepository.com/artifact/org.jcodec/jcodec/0.2.0
