### ISSUE TITLE
AWTSequenceEncoder8Bit and Flag don't exist

### ISSUE THREAD

**Issue by amiga** [jcodec/jcodec#208]
Trying this sample https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/gen/SequenceEncoderDemo.java

But I cannot import :
import org.jcodec.common.tools.MainUtils.Flag;
import org.jcodec.api.awt.AWTSequenceEncoder8Bit;

**Comment by PhotoInspirations** [comment]
Are you using the current version of jcodec, or an earlier one such as 0.1.9 (which does not appear to have those two items)?

**Comment by svitvitskiy** [comment]
You probably didn't have jcodec 0.2.0 and jcodec-javase 0.2.0 in your maven dependencies. Try specifying this in your pom.xml:
```xml
<dependency>
  <groupId>org.jcodec</groupId>
  <artifactId>jcodec</artifactId>
  <version>0.2.0</version>
</dependency>
<dependency>
  <groupId>org.jcodec</groupId>
  <artifactId>jcodec-javase</artifactId>
  <version>0.2.0</version>
</dependency>
```
And AWTSequenceEncoder8Bit doesn't exist anymore, simply use AWTSequenceEncoder now. This class only existed in the snapshot as a temporary measure.
