### ISSUE TITLE
Images to mp4

### ISSUE THREAD

**Issue by tobibo** [jcodec/jcodec#21]
Hope its ok to post this here, but didn't know where else.

I got it kind of working but, i can't get the correct delays working. I basically want a gif like animation of pictures. So when i use this line to add frame i don't quite understand the parameters:

```
    int timescale = 25;
FramesMP4MuxerTrack outTrack = muxer.addTrackForCompressed(TrackType.VIDEO, timescale);

// Create H.264 encoder

H264Encoder encoder = new H264Encoder(); // not we could use a
// rate
// control in the
// constructor

// Allocate a buffer that would hold an encoded frame
ByteBuffer _out = ByteBuffer.allocate(height * width * 6); // Not sur
// about
// RGB

// Allocate storage for SPS/PPS, they need to be stored
// separately
// in a special place of MP4 file
ArrayList<ByteBuffer> spsList = new ArrayList<ByteBuffer>();
ArrayList<ByteBuffer> ppsList = new ArrayList<ByteBuffer>();




options.inSampleSize = imageWidth / 320;
for (int i = 0; i < images.size(); i++) {
    Bitmap bitmap = BitmapFactory.decodeFile(images.get(i),
    options);
    Picture img = fromBitmap(bitmap);

    Picture yuv = Picture.create(img.getWidth(), img.getHeight(), ColorSpace.YUV420);
    transform.transform(img, yuv);

    img = null;
    _out.clear();
    ByteBuffer result = encoder.encodeFrame(_out, yuv); //toEncode

    // Based on the frame above form correct MP4 packet
    spsList.clear();
    ppsList.clear();
    H264Utils.encodeMOVPacket(result, spsList, ppsList);

    outTrack.addFrame(new MP4Packet(result, i, timescale, 1, speed, true, null, i, 0));

    result = null;

}
outTrack.addSampleEntry(H264Utils.createMOVSampleEntry(spsList, ppsList));
muxer.writeHeader();
```

Can someone explain those parameters, especially the one at this line:

```
   outTrack.addFrame(new MP4Packet(result, i, timescale, 1, speed, true, null, i, 0));
```

I just want each frame to have a certain duration/delay. Can anyone help?

**Comment by quangjimy99** [comment]
Hi i use jcodec but i have a error
SequenceEncoder se = null;
try {
se = new SequenceEncoder(new File(
params[0].getParentFile(), "jcodec_enc.mp4"));
File img = new File("/mnt/sdcard/aamymap",
"Cap1"+".PNG");
File img2 = new File("/mnt/sdcard/aamymap",
"Cap2"+".PNG");
Bitmap frame = BitmapFactory.decodeFile(img
.getAbsolutePath());
se.encodeImage(frame);
Bitmap frame2 = BitmapFactory.decodeFile(img2
.getAbsolutePath());
se.encodeImage(frame2);
se.finish();

        } catch (IOException e) {
            Log.e(TAG, "IO", e);
        }
Line se.encodeImage(frame2); always error 
Please help me. Thank

**Comment by longwayto** [comment]
Hello，I want to know how to set video loop. If i give 5 frame,and want it play 5 frame twice,how to do with jcodec

**Comment by svitvitskiy** [comment]
You can either add 5 frames twice or create an edit list with two edits. If
you want to use editlist just create two identical edits from zero to the
duration of the movie and increase the movie duration 2x .

Let me know if you need a code snippet.

Oh and if your target player for some reason doesn't support edits, you can
create a loop by pointing the samples from your mp4 header to the same
media data.

Stan

**Comment by vocalist** [comment]
what is problem of this code ? I used this code but generated file is not playable.
public boolean initialize() {
        Log.e("jcodec error","initialize started" );
        mSpsList = new ArrayList<>();
        mPpsList = new ArrayList<>();
        frameNo = 0;
        try {
            mChannelWrapper = NIOUtils.writableFileChannel(getOutputFilePath());
            mMp4Muxer       = new MP4Muxer(mChannelWrapper, Brand.MP4);
            mMp4Muxer.addTrack(TrackType.VIDEO, getFrameRate());
            mMp4Track = new FramesMP4MuxerTrack(mChannelWrapper,0,TrackType.VIDEO,getFrameRate());
            mMp4Track.setTgtChunkDuration(new Rational(2, 1), Unit.SEC);
            initialized = true;
            Log.e("jcodec error","initialize finished" );
            return true;
        } catch (IOException e) {
            Log.e("jcodec initail",e.getMessage());
        }

        return false;
    }

    int getFrameRate(){
        return 30000;
    }

    void addFrame(byte[] data) {
        long timescale = getFrameRate();
        ByteBuffer buffer = ByteBuffer.wrap(data);
        H264Utils.encodeMOVPacket(buffer);

        try {
            frameNo++;
            long temp = frameNo*1001+1001;
            mMp4Track.addFrame(
                    new MP4Packet(
                            buffer,
                            temp,
                            timescale,
                            1001,
                            frameNo,
                            true,
                            null,
                            temp,
                            0)
            );
        } catch (IOException e) {
            Log.e("jcodec error",e.getMessage() );
        }
    }

**Comment by tianqiujie** [comment]
I custom a sequence:

public void encodeNativeFrame(Picture pic, long duration) throws IOException {
        if (toEncode == null) {
            toEncode = Picture.create(pic.getWidth(), pic.getHeight(), encoder.getSupportedColorSpaces()[0]);
        }

        // Perform conversion
        transform.transform(pic, toEncode);

        // Encode image into H.264 frame, the result is stored in '_out' buffer
        _out.clear();
        ByteBuffer result = encoder.encodeFrame(toEncode, _out);

        // Based on the frame above form correct MP4 packet
        spsList.clear();
        ppsList.clear();
        H264Utils.wipePS(result, spsList, ppsList);
        H264Utils.encodeMOVPacket(result);

        // Add packet to video track
        outTrack.addFrame(new MP4Packet(result, frameNo, 25, duration, frameNo, true, null, frameNo, 0));

        frameNo++;
    }


and call it:
Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
            ISequenceEncoder sequenceEncoder = new ISequenceEncoder(new File(name));
            sequenceEncoder.encodeImage(bitmap, (long) (2000 / 25f));


But not work

**Comment by opg7371** [comment]
When the video is created successfully, then the duration showed on the video anywhere on the video thumbnail is 0.0 sec however the video runs successfully for the required time. Can anyone suggest me on how to set the duration of a video?
@tobibo @svitvitskiy @app12
