### ISSUE TITLE
SequenceEnconderDemo 

### ISSUE THREAD

**Issue by ofSaJoaquim** [jcodec/jcodec#221]
I can't make this work. I  didn't understand how pass the paramenters. I tried and return this:
Exception in thread "main" java.lang.IllegalStateException: Can not save header with 0 tracks.
Is there someone exemple for SequenceEnconderDemo, AWTSequenceEncoder our SequenceEnconder with  jcodec2.0?

**Comment by svitvitskiy** [comment]
The way you use org.jcodec.samples.api.SequenceEncoderDemo is by specifying a pattern for a bunch of images that will be encoded as a video. For instance if I had a bunch of PNG images called 'frame_000.png' ... 'frame_nnn.png' you would run it with an argument:
`--out-pattern=frame_%03d.png`
I know, the argument name is kind of confusing, I'll rename it to 'input-pattern'. Also when no input files are found for the input pattern the exception is thrown which is obviously a bug, I'll have a PR for that.

**Comment by svitvitskiy** [comment]
Please refer to this [PR](https://github.com/jcodec/jcodec/pull/222) for the updated parameter.
