### ISSUE TITLE
new SequenceEncoder(new File("location")) is not available

### ISSUE THREAD

**Issue by HasnainAD** [jcodec/jcodec#251]
I was looking different code samples here and on stackoverflow. In all those codes
`new SequenceEncoder(new File()) `has been used.` `But in android its constructor uses:

```
new SequenceEncoder(SeekableByteChannel, Rational).
```
How is this alternative of 
```
new SequenceEncoder(new File());
```

**Comment by svitvitskiy** [comment]
This is to be able to specify your frame rate. So if for instance your video is 25 fps you would use something like this:

```
new SequenceEncoder(file, new Rational(25, 1));
```

If your frame rate is 29.97 (as in NTSC) you would use something like:

```
new SequenceEncoder(file, new Rational(3000, 1001));
```

Please refer to [SequenceEncoderDemo](https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/api/SequenceEncoderDemo.java) for the sample usage of the class.
