### ISSUE TITLE
Error in license

### ISSUE THREAD

**Issue by Gamebuster19901** [jcodec/jcodec#265]
The license says "Redistributions of  source code  must  retain the above  copyright notice" but there is no copyright notice above in the file. I also noticed the same thing on your website: http://jcodec.org/lic.html

A copyright notice is structured as follows: 
Copyright © <year>, <copyright holder(s)>

**Comment by zhuker** [comment]
does this work?
https://github.com/jcodec/jcodec/pull/267/files

**Comment by svitvitskiy** [comment]
Fixed
