### ISSUE TITLE
Can't play .h264 file

### ISSUE THREAD

**Issue by mahmoud-bahaa** [jcodec/jcodec#269]
I'm using ExtractorMediaSource to play .h264, however the exact mp4 content plays fine. I get the following error when I try to play the file: java.lang.IllegalStateException: Top bit not zero: -7615023332543036719
Is there another extractor I should be using?

**Comment by svitvitskiy** [comment]
I don't think your problem is related to JCodec. Looking at the class name tells me this is something related to ExoPlayer.
