### ISSUE TITLE
One question about license. 

### ISSUE THREAD

**Issue by mohzhang** [jcodec/jcodec#30]
From jcodec readme:
JCodec is free software distributed under FreeBSD License.

But in some source files:
/**
* JEBML - Java library to read/write EBML/Matroska elements.
* Copyright (C) 2004 Jory Stone <jebml@jory.info>
* Based on Javatroska (C) 2002 John Cannon <spyder@matroska.org>
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.
*
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*/

Does this affect jcodec's FreeBSD license?

**Comment by svitvitskiy** [comment]
This GPLed code was taken as a temporary solution to speed up our own implementation of MKV.

The code in question has been already removed.

Thanks for pointing out.
