### ISSUE TITLE
No runnable processing and very slow process

### ISSUE THREAD

**Issue by aceylan** [jcodec/jcodec#303]
Hi. i have a problem. 
i am developing a program for creating video on android. I will paste a code example. it is for just 100 frames. But it is creating video in 5 minutes for 4 seconds video with samsung galaxy note 3. 
And runnable is not working. because i wanted to set text of a textview for each frame, but it is not working. process is locking program. 
Sorry for my english. the codes are below. 

` txtHw=(TextView)findViewById(R.id.txthelloworld);
        btnVideo=(Button)findViewById(R.id.btnVideo);

        btnVideo.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        File folder = new File(Environment.getExternalStorageDirectory() + "/ytb");
                        boolean success = true;
                        if (!folder.exists()) {
                            success = folder.mkdir();
                        }
                        if (success) {
                            // Do something on success
                        } else {
                            // Do something else on failure
                        }
                        SeekableByteChannel out = null;
                        try {
                            out = NIOUtils.writableFileChannel(Environment.getExternalStorageDirectory()
                                    + File.separator + "ytb"+File.separator +"output.mp4");
                            // for Android use: AndroidSequenceEncoder
                            AndroidSequenceEncoder encoder = new AndroidSequenceEncoder(out, Rational.R(25, 1));
                            Bitmap image;
                            //image = BitmapFactory.decodeFile(Environment.getExternalStorageDirectory()+ File.separator + "ytb"+File.separator + "22.jpg");
                            image=Bitmap.createBitmap(1280, 720, Bitmap.Config.ARGB_8888);
                            image.eraseColor(android.graphics.Color.GREEN);
                            for (int i=0;i<100;i++) {
                                txtHw.setText(String.valueOf(i));

                                // Generate the image, for Android use Bitmap

                                if (i<25 ){
                                    image=Bitmap.createBitmap(1280, 720, Bitmap.Config.ARGB_8888);
                                    image.eraseColor(android.graphics.Color.YELLOW);
                                    //    image = BitmapFactory.decodeFile(Environment.getExternalStorageDirectory()+ File.separator + "ytb"+File.separator + "22.jpg");
                                }else if(i<50){
                                    image=Bitmap.createBitmap(1280, 720, Bitmap.Config.ARGB_8888);
                                    image.eraseColor(android.graphics.Color.RED);
                                    //  image = BitmapFactory.decodeFile(Environment.getExternalStorageDirectory()+ File.separator + "ytb"+File.separator + "36.jpg");
                                }else if(i<75){
                                    image=Bitmap.createBitmap(1280, 720, Bitmap.Config.ARGB_8888);
                                    image.eraseColor(android.graphics.Color.BLUE);
                                    //  image = BitmapFactory.decodeFile(Environment.getExternalStorageDirectory()+ File.separator + "ytb"+File.separator + "46.jpg");
                                }

                                // Encode the image
                                encoder.encodeImage(image);
                            }
                            // Finalize the encoding, i.e. clear the buffers, write the header, etc.
                            encoder.finish();
                            txtHw.setText("finish");
                        } catch (FileNotFoundException e) {
                            e.printStackTrace();
                            txtHw.setText("error");
                        } catch (IOException e) {
                            e.printStackTrace();
                            txtHw.setText("error");
                        } finally {
                            NIOUtils.closeQuietly(out);
                        }

                    }
                });`

**Comment by xardazz** [comment]
I can't answer your original question about speed of processing, but regarding "program locking" - what did you except when submitting the long running Runnable to UI thread (line  runOnUiThread(new Runnable()). The main processing should be held in separate non-UI thread.

**Comment by aceylan** [comment]
I solve the problem with asynctask. Thanks for reply. 
It is slowly still. But i dont need animation. I made fps 25 to 1. it is more fast now.

**Comment by zhuker** [comment]
@aceylan 
https://github.com/jcodec/jcodec#performance--quality-considerations
