### ISSUE TITLE
Increase Time interval of video in Android

### ISSUE THREAD

**Issue by IamSantosh** [jcodec/jcodec#305]
With the help of jcodec, I'm able to make a video from images(bitmap) in android but I'm not finding a way to increase interval of the video. Video just start and finish showing all images very fast. I'm using this code.

SeekableByteChannel out = null;
try {
    out = NIOUtils.writableFileChannel(filePath);
    AndroidSequenceEncoder encoder = new AndroidSequenceEncoder(out, Rational.R(25, 1));
    for (int i=0;i<Constants.selectedImagesBitmap.size();i++) {
        Bitmap image = Constants.selectedImagesBitmap.get(i) ;
        encoder.encodeImage(image);
    }
    encoder.finish();
} catch (FileNotFoundException e) {
    e.printStackTrace();
} catch (IOException e) {
    e.printStackTrace();
} finally {
    NIOUtils.closeQuietly(out);
} 

I just want each frame to have a certain duration/delay. Can anyone help?

**Comment by mazid1** [comment]
@IamSantosh How did you solve the problem? I am facing the same problem now.

**Comment by IamSantosh** [comment]
@mazid1 
in line AndroidSequenceEncoder encoder = new AndroidSequenceEncoder(out, Rational.R(25, 1));
just decrease the value of 25 to 1. By doing this, you will see the difference in time interval.
