### ISSUE TITLE
When i make a mp4 out of BufferedImages it is invalid

### ISSUE THREAD

**Issue by thatmadhacker** [jcodec/jcodec#306]
Im using this code to create videos from bufferedimages:
`AWTSequenceEncoder se = new AWTSequenceEncoder(new File("vid.mp4")); `
`for(BufferedImage frame : frames){`
`		se.encodeNativeFrame(AWTUtils.fromBufferedImageRGB(frame));`
`		}`
`		`
`		se.finish();`
but when i run it it finishes and generates a video file but the file is not valid, it is detected as corrupted/invalid by windows
i am using jcodec version 0.1.9 because my other code does not work with newer versions

**Comment by svitvitskiy** [comment]
Hi,
0.1.9 is not a supported version anymore. But I am wondering if this is still a problem in 0.2.x. Which version of Windows are you trying it on?

**Comment by thatmadhacker** [comment]
windows 10

**Comment by thatmadhacker** [comment]
also the AWTSequenceEncoder and AWTUtils are not in that version of jcodec so i copied the classes over that might be part of the problem.

**Comment by svitvitskiy** [comment]
You need to include jcodec-javase project in your maven deps

**Comment by thatmadhacker** [comment]
also the amount of time it takes to grab 1 single frame is way too long, it takes around 1200 ms per frame to just get it

**Comment by svitvitskiy** [comment]
Performance optimizing decoders is an ongoing process. Please adjust your expectations, it will not work at the speed of native decoder. [Please refer here](https://github.com/jcodec/jcodec#performance--quality-considerations)
