### ISSUE TITLE
AWTUtil removed from Jcodec 0.2.2?

### ISSUE THREAD

**Issue by l0v3w4v3** [jcodec/jcodec#307]
I've just applied jcodec 0.2.2 to my project and tried to following the sample code to get a single thumbnail of a video but I cannot find the AWTUtil class. Is this removed? What is the alternative choice for this?

**Comment by ddalcu** [comment]
You have to include the jcodec-javase dependency.

		<dependency>
			<groupId>org.jcodec</groupId>
			<artifactId>jcodec-javase</artifactId>
			<version>0.2.2</version>
		</dependency>
