### ISSUE TITLE
Generating streaming MP4 video

### ISSUE THREAD

**Issue by jameadows** [jcodec/jcodec#31]
Hi,

I need to generate streaming MP4 video from bitmaps that will be generated by java code.  I've been looking over the JCodec code and think it might work for this but I'm hoping someone on the project can confirm or deny that.  MP4 isn't a hard requirement, but the generated video will be displayed in a web browser and MP4 seems to have the broadest support at this time.  But if there's an alternative that'd be good to know too.

Thanks in advance,
Joe

**Comment by svitvitskiy** [comment]
Yes, jcodec will allow you to generate MP4/h.264 video from a bunch of bitmaps.
