### ISSUE TITLE
JDK requirement and getting frame of video from inputstream

### ISSUE THREAD

**Issue by l0v3w4v3** [jcodec/jcodec#313]
Does this library require JDK 7 to run? Am I able to use it on JDK 6?
How can I grab a frame of video from inputstream instead of the file?

**Comment by zhuker** [comment]
jcodec does work on JDK6

re inputstream
what is the codec/format you are trying to decode/demux?
normally video formats really want underlying media to be seekable. since `InputStream` is not seekable only several codec/format combinations can technically be decoded/demuxed from `InputStream`

**Comment by l0v3w4v3** [comment]
The format is mp4.
I'm gonna work with avi, mov and flv in near future.
In this case which of them can help?

**Comment by svitvitskiy** [comment]
MP4 will require random access functionality so InputStream won't work.

**Comment by l0v3w4v3** [comment]
Alright, thanks for your help!
