### ISSUE TITLE
How to read video metadata like comments, author etc?

### ISSUE THREAD

**Issue by goodidea-kp** [jcodec/jcodec#314]
Can someone provide an example how to read video metadata, like author, comments, album etc? As far as formats are different it is not clear how to read let's say from MKV.

**Comment by svitvitskiy** [comment]
I am not sure we support this with MKV. In case of MP4 this is possible. Please see [this article](http://jcodec.org/docs/working_with_mp4_metadata.html).

**Comment by goodidea-kp** [comment]
I saw that. It return unsupported format for MKV.
