### ISSUE TITLE
java.lang.UnsupportedException when calling org.jcodec.api.FrameGrab.createFrameGrab

### ISSUE THREAD

**Issue by drcgjung** [jcodec/jcodec#332]
This relates to master (0.2.4-SNAPSHOT) under Java 7

Calling code:
 FileChannelWrapper wrap=new FileChannelWrapper(new FileInputStream(args[0]).getChannel());
 FrameGrab frameGrab1 = FrameGrab.createFrameGrab(wrap);

File is located here

https://drive.google.com/open?id=1jAcN2NE5xC7U4FtArG28-Y4APmaHuuNV

Results in 
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161)
	at org.jcodec.containers.mp4.boxes.NodeBox.findBox(NodeBox.java:206)
	at org.jcodec.containers.mp4.boxes.NodeBox.findAllPath(NodeBox.java:183)
	at org.jcodec.containers.mp4.boxes.NodeBox.findAll(NodeBox.java:169)
	at org.jcodec.containers.mp4.demuxer.MP4Demuxer.processHeader(MP4Demuxer.java:89)
	at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:84)
	at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:75)
	at org.jcodec.containers.mp4.demuxer.MP4Demuxer.createMP4Demuxer(MP4Demuxer.java:48)
	at org.jcodec.api.FrameGrab.createFrameGrab(FrameGrab.java:59)

The findBox code likes to first remove the head of the path and later reattach it

    public static void findBox(Box root, List<String> path, Collection<Box> result) {
    
        if (path.size() > 0) {
            String head = path.remove(0);
            if (root instanceof NodeBox) {
                NodeBox nb = (NodeBox) root;
                for (Box candidate : nb.getBoxes()) {
                    if (head == null || head.equals(candidate.header.getFourcc())) {
                        findBox(candidate, path, result);
                    }
                }
            }
            path.add(0, head);
        } else {
            result.add(root);
        }
    }

But the list that is been presented by the calling findAllPath code is not removeable, since Arrays.asList produces some leightweight immutable List object on top of the path array.

    public static <T extends Box> T[] findAllPath(Box box, Class<T> class1, String[] path) {
        List<Box> result = new LinkedList<Box>();
        findBox(box, Arrays.asList(path), result);
    
        for (ListIterator<Box> it = result.listIterator(); it.hasNext();) {
            Box next = it.next();
            if (next == null) {
                it.remove();
            } else if (!Platform.isAssignableFrom(class1, next.getClass())) {
                // Trying to reinterpret one box as the other
                try {
                    it.set(Box.asBox(class1, next));
                } catch (Exception e) {
                    Logger.warn("Failed to reinterpret box: " + next.getFourcc() + " as: " + class1.getName() + "."
                            + e.getMessage());
                    it.remove();
                }
            }
        }
        return result.toArray((T[]) Array.newInstance(class1, 0));
    }

So my proposal to fix it:

    public static <T extends Box> T[] findAllPath(Box box, Class<T> class1, String[] path) {
        List<Box> result = new LinkedList<Box>();
        findBox(box, new ArrayList<String>(Arrays.asList(path)), result);

**Comment by zhuker** [comment]
@drcgjung pull from master again i just fixed it

**Comment by drcgjung** [comment]
Great, just checked master. Works. you are the best!
