### ISSUE TITLE
Problem when extracting frames from a video with the example in the wiki

### ISSUE THREAD

**Issue by ajilizz** [jcodec/jcodec#335]
Hello everyone,

First of all thank you for the library and the work you put into it

I'm just a beginner in coding and image processing. 
Basically, I'm trying to extract all frames from a MP4 video file encoded in H264 with 30 fps.
It seems to work fine, I can save the frames in the folder I want but when I vizualise the frames one after an other the problem appears : every few frames I don't get the frame I'm supposed to get but the 4th or 5th previous frame.

I don't understand why this is happening, I've tried with the " Getting a single frame from a movie " sample code with a while loop and the " Get all frames from a video file " sample.

Here is the code I used for the " Get all frames from a video file " sample :

public class AllFramesExtracter 
{

    public static void main( String[] args ) throws IOException, JCodecException
        {
        
        Picture picture;
        String videoName = "video_jeanne_2";
        int frameNumber = 0;
        File file = new File("././affluence_sample/" + videoName + ".mp4");
        
		FrameGrab grab = FrameGrab.createFrameGrab(NIOUtils.readableChannel(file));
		
		while (null != (picture = grab.getNativeFrame())) {
			
		    System.out.println(picture.getWidth() + "x" + picture.getHeight() + " " + picture.getColor());
		    BufferedImage bufferedImage = AWTUtil.toBufferedImage(picture);
		    String pathForExtractedImage = "././affluence_sample/" + videoName + "/frame " + frameNumber +".png";
		    ImageIO.write(bufferedImage, "png", new File(pathForExtractedImage));
		    frameNumber ++;
		}
		
    }
}
`

**Comment by svitvitskiy** [comment]
From what you are describing it seems like the frames in your file might be reordered. Reordering is necessary to encode videos with B-frames (the frames that reference both previous and 'future' frame). 

Frame grab doesn't keep a buffer and gives you the frames as they come in a file (decoding order). At this point you will have to reorder your frames according to their PTS (Presentation TimeStamp). For this you need to be calling 'getNativeFrameWithMetadata' which returns you the object that has the decoded picture as well as the PTS.
Then you'll just keep a sorted list of pictures (say the last 10 pictures). So at the beginning you add 10 pictures to the list, then for each decoded picture you add it to the list and output the one with the lowest PTS from the list. At the end of decoding you flush everything on your list.

**Comment by jamestomk** [comment]
I notice that your 'picturesWithMetadata' is an ArrayList, which will be ordered by the sequence of ".add()" calls (append to end of list), not necessarily by the order of the meta.getTimestamp().   You should be using something like an Ordered Map:
`java.util.SortedMap<Double,Picture> sortedPictures = new TreeMap<Double,Picture>();`
and insert with:
`sortedPictures.put( pwm.getTimestamp(), pwm.getPicture() );`
which will re-sort the list on any out-of-order timestamps.  Then you could retrieve with 
`for ( Entry<Double, Picture> frameEntry : sortedPictures.entrySet() ) `
