### ISSUE TITLE
Convert MPEG4 codec to H264 codec

### ISSUE THREAD

**Issue by avanibhatnagar** [jcodec/jcodec#350]
Hey,

I have a .mp4 file (video+audio - which I created from a sequence of images) with MPEG4 codec, and I want to convert it to H264 codec since most browsers support that, it would be great if you could help me guide how to do that...

I'm not sure if this is the right place to ask this (Apologizing in advance, if it isn't..)! I couldn't find a sample that was related to this..

**Comment by svitvitskiy** [comment]
Though theoretically possible, I wouldn't recommend doing it with jcodec. There are multiple reasons for that including output quality and the speed of encoding. I would recommend using ffmpeg.

**Comment by avanibhatnagar** [comment]
I used javacv(java interface to FFMPEG) to create a video but I'm unable to change the encoding to H264 after several tries, and I need to codec to be H264. I don't care about quality and speed at this time. How should I go about it using jcodec?
