### ISSUE TITLE
[Android] Unable to create >1 FPS video using AndroidSequenceEncoder

### ISSUE THREAD

**Issue by bartoszpalka** [jcodec/jcodec#355]
I'd like to create boomerang alike video (slideshow back and forth) using AndroidSequenceEncoder. I've managed to create video, but it looks like the FPS param in createSequenceEncoder method does not work. The goal is to achieve 75 ms delay between subsequenced encoded bitmaps but now all I can get is more or less 1 FPS. Am I missing something?

Used code:
```
AndroidSequenceEncoder ase = null;
String imageFileName = "video.mp4";
File finalVideoFilePath = new File(eventPhotosTempStorageDir, imageFileName);
Integer fps = 14;

try
{
        ase = AndroidSequenceEncoder.createSequenceEncoder(finalVideoFilePath, fps);
        for (int i = 1; i < photos.size(); i++) {
             for (int j = 0; j < fps; j++)
             {
                   ase.encodeImage(bitmaps.get(i));
             }
       }
       ase.finish();
} 
catch (Exception e) 
{
            e.printStackTrace();
}
```

**Comment by svitvitskiy** [comment]
If I read your code correctly it seems that you are adding each image 14
times, so you will get 1 frame per second (or 14 bit exact frames per
second).

**Comment by bartoszpalka** [comment]
Indeed, you are clearly right! I thought that even if I'm declaring desired FPS rate I'd still have to take care of each subsequent frame. Thank you for your help.
