### ISSUE TITLE
Matrix Structure is destroyed when add metadata

### ISSUE THREAD

**Issue by ShinjiYoshimori** [jcodec/jcodec#366]
Hello

I typed the below command to insert metadata into a captured video by Android phone.
./metaedit -sk metadata=foobar input_video.mp4

I found out that the metadata was inserted but there is a problem with rotation for the video.
Original file is portrait but converted one is landscape.

I checked the video information by exiftool and it seems that the matrix structure may be destroyed.
I've attached the videos and information texts as zip file.

Could you please check it out?
I would like to know how to avoid this problem.
Thanks 

[ metadata.zip includes]
 - input_video.mp: original video file
 - .input_video.mp: converted video file
 - before_info.txt:  the information of original video file by exiftool
 - after_info.txt:  the information of converted video file by exiftool

[metadata.zip](https://github.com/jcodec/jcodec/files/2956138/metadata.zip)

**Comment by svitvitskiy** [comment]
Thank you for reporting. I'll have a look.

**Comment by svitvitskiy** [comment]
I believe this has been fixed. The link on the [documentation page](http://jcodec.org/docs/working_with_mp4_metadata.html) has been updated.

**Comment by ShinjiYoshimori** [comment]
Thanks for your action.
I tested a new metaedit tool and it work!
That's great!

Since I would like to insert metadata into videos by Android application on Android OS,
I'd like to know if java source code for metaedit on the git hub has been updated and work like a binary metaedit tool.

Thanks

**Comment by svitvitskiy** [comment]
The answer is yes. Metaedit tool is basically jcodec.jar with manifest.

**Comment by ShinjiYoshimori** [comment]
That's wonderful.Thanks.

**Comment by ShinjiYoshimori** [comment]
Sorry I checked this by two ways.
1. Download all source code and put them into a test project on Android Studio 
2. Using the latest version of jcodec-0.2.3.jar

1st way work out this issue but 2nd one did not.
I prefer 2nd one because it's easier to implement and maintain than 1st

Could you please check it out and if you could apply this patch to the latest version of jcodec jar?

**Comment by ShinjiYoshimori** [comment]
Sorry but any updates on this?

**Comment by svitvitskiy** [comment]
Working on it, I'll let you know.

**Comment by ShinjiYoshimori** [comment]
I'm happy if  there would be any updates on this.

**Comment by svitvitskiy** [comment]
Yeah, so I pushed jcodec.jar but haven't pushed everything around it, like javase, android etc. Will do ASAP.

**Comment by svitvitskiy** [comment]
Ok, pushed jcodec,javase,android 0.2.5 to maven central, take a look.

**Comment by ShinjiYoshimori** [comment]
Thanks a lot.
I tested the latest version 0.2.5 and it works now.
I'll test more a bit.
