### ISSUE TITLE
This conditional block will always fail with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ilyazolotarov** [jcodec/jcodec#367]
https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/codecs/h264/io/model/PictureParameterSet.java#L179-L187

**Comment by svitvitskiy** [comment]
Fixed in https://github.com/jcodec/jcodec/commit/cd6efa51ef05f409a8ba8cfb7521f4b4f10ccc75
