### ISSUE TITLE
Extracting AppleGPS Coordinates from an MP4

### ISSUE THREAD

**Issue by whisere** [jcodec/jcodec#372]
Hello we are having problem extracting AppleGPS Coordinates from an MP4, we can find the box with the AppleGPS Coordinates in it, but  can't figure out how to extract the string from the Box$LeafBox with id "©xyz"... any suggestion is much appreciated!

**Comment by zhuker** [comment]
can you post a sample file here?

**Comment by whisere** [comment]
@zhuker Please see the two files as zip here Thanks. 
[files.zip](https://github.com/jcodec/jcodec/files/3146677/files.zip)

**Comment by zhuker** [comment]
@whisere

**Comment by zhuker** [comment]
@whisere 
this is how you do it in hacky way
https://github.com/jcodec/jcodec/commit/a5c0c1cb4c190634ab09fb02354db0d6a4fe9e5e

i added a nicer way in PR #373

## Parse Apple GPS metadata from MOV or MP4 file
```java
MovieBox moov = MP4Util.parseMovie(new File("gps1.mp4"));
UdtaBox udta = NodeBox.findFirst(moov, UdtaBox.class, "udta");
String latlng = udta.latlng();
assertEquals("-35.2840+149.1215/", latlng);
```

OR

```java
MovieBox moov = MP4Util.parseMovie(new File("gps2.MOV"));
MetaBox meta = NodeBox.findFirst(moov, MetaBox.class, "meta");
String latlng1 = meta.getKeyedMeta().get("com.apple.quicktime.location.ISO6709").getString();
assertEquals("-35.2844+149.1214+573.764/", latlng1);
String latlng2 = meta.getItunesMeta().get(1).getString();
assertEquals("-35.2844+149.1214+573.764/", latlng2);

``` 
@svitvitskiy

**Comment by whisere** [comment]
@zhuker Thank you! That's brilliant!

**Comment by tballison** [comment]
W00t!  Thank you @zhuker !
