### ISSUE TITLE
MKV Subtitle extraction support..?

### ISSUE THREAD

**Issue by wordlessly** [jcodec/jcodec#374]
Hi,

it would be nice to be able to export subtitles in a MKV to something like SRT. MKVDemuxer seems to only focus on Video and Audio. Any plans to extend this?

**Comment by zhuker** [comment]
post a small sample mkv with subs file here (preferably less than 10MB), i'll add support for it

**Comment by wordlessly** [comment]
The test5.mkv from https://github.com/Matroska-Org/matroska-test-files seems suitable. Thanks!

**Comment by zhuker** [comment]
@wordlessly just added PR #375 for it
```java
MKVDemuxer demuxer = new MKVDemuxer(new AutoFileChannelWrapper(new File("subs.mkv")));
DemuxerTrack track = demuxer.getSubtitleTracks().get(0);
Packet packet;
while (null != (packet = track.nextFrame())) {
    String text = takeString(packet.getData());
    System.out.println("time: " + packet.pts + " text: " + text);
}
```

you get
```
0 time: 1549 text: ...the colossus of Rhodes!
1 time: 3757 text: No!
2 time: 4715 text: The colossus of Rhodes
and it is here just for you Proog.
```

**Comment by zhuker** [comment]
@svitvitskiy
