### ISSUE TITLE
Java 9 modules for jcodec and jcodec-se

### ISSUE THREAD

**Issue by priyanahata** [jcodec/jcodec#399]
When trying to use jcodec-javase in a modular application, the jvm's module loader complains aboutjcodec and jcodec-javase having two packages with the same name hence causing a (....dramatic music...) 'unsolvable jigsaw'

Would it be possible to move the class SoundUtil from org.jcodec.common and AWTUil in org.jcodec.scale in jcodec-javase to a different package that does not exist in jcodec (e.g. org.jcodec.javase.common and org.jcodec.javase.scale or something like that)  and increase the release version adding (again dramatic music) Java 9+ Jigsaw ***modular application*** Suuuupppooorrt

I can do that if you want

**Comment by svitvitskiy** [comment]
Hi, yes, please send a pull request for the feature. I'll merge and make the release.

**Comment by caraiz** [comment]
Hi, same problem here, im using openjdk-13 and jcodec-0.2.5

is there some advance in it?

Thanks.

**Comment by svitvitskiy** [comment]
Fixed in a0bc5021
