### ISSUE TITLE
H264Decoder decodeFrame not return.

### ISSUE THREAD

**Issue by nguyentrungduc08** [jcodec/jcodec#407]
I've use H264Decoder with decodeFrame function to decode frame I attached below.
File error.h264 like never return or throw any exception.

[h264Frame.zip](https://github.com/jcodec/jcodec/files/4372696/h264Frame.zip)

**Comment by djdjdjek** [comment]
Hi, I have the same problem, but I feed the decoder with raw data in byte array. This code will get 'null' from decoder, but I dont know why?

```
byte[] sps = [0x00 0x00 0x00 0x01 0x67....]
byte[] pps = [0x00 0x00 0x00 0x01 0x68....] 
byte[] iFrame = [0x00 0x00 0x00 0x01 0x65....] 
byte[] pFrame = [0x00 0x00 0x00 0x01 0x61....] 
List<ByteBuffer> spsList = new ArrayList<ByteBuffer>();
List<ByteBuffer> ppsList = new ArrayList<ByteBuffer>();

ByteBuffer bb = ByteBuffer.allocate(1280 * 720 * 6);
H264Decoder decoder = new H264Decoder();
bb.put(sps);
spsList.add(bb);
bb = ByteBuffer.allocate(1280 * 720 * 6);
bb.put(pps);
ppsList.add(bb);

decoder.addSps(spsList);
decoder.addPps(ppsList);

bb = ByteBuffer.allocate(1280 * 720 * 6);
bb.put(iFrame);
List<ByteBuffer> iframeList = new ArrayList<ByteBuffer>();
iframeList.add(bb);

Picture buf = Picture.create(1280 << 4, 720 << 4, ColorSpace.YUV420);
Picture dec = decoder.decodeFrame(bb, buf.getData());
```

dec    >>>>  will get 'null'

**Comment by njsfzj** [comment]
Hi,
How to make H264Decoder decode pFrame? It seems the decoder only works for iFrame...

Many thanks!

**Comment by nguyentrungduc08** [comment]
Yes, The decoder can only decode I-frame

**Comment by svitvitskiy** [comment]
Hi, the decoder can decode all types of frames, that is I-frames, P-frames and B-frames. You can refer to the class called FrameGrab to see how that's done.

nguyentrungduc08@ thank you for sharing the sample frames, could you also share a code sample so I can take a look.

njsfzj@ Could you share your sample code and the sample streams you are using, also are you using jcodec from HEAD or some other version?

djdjdjek@ I don't see you actually feeding a p-frame to the decoder, maybe it's outside of the code sample. Could you share the input frames you were using as well as more complete code sample?

Thanks.
