### ISSUE TITLE
MetadataEditor doesn't close Filehandle and leaves tempory files there

### ISSUE THREAD

**Issue by Nirostar** [jcodec/jcodec#410]
I use a Muxer to merge two m4a files and then I use the MetadataEditor to change the iTunesMetadata in them. After the save method finishes, there are two files: the original one and a Tempfile starting with ".". The original File is not tagged. The writing on the hard drive also hasn't finished at this point in time. The file also remains open. Is this a bug, or am I doing something wrong?

**Comment by svitvitskiy** [comment]
thanks! I can take a look. If you fix the bug I'll be happy to merge you PR though.

**Comment by Nirostar** [comment]
I'm not quite sure where exactly the error lies. I figured out, that this is only a problem if the fast parameter is false. But I need this or MusicBee won't recognize the tags.

**Comment by Nirostar** [comment]
I found the culprit but I am not quite able to fix it. I am very new to GitHub and don't really know how to properly do a PR. May you fix it?

`SeekableByteChannel[][] inputs` in `org.jcodec.movtool.Flattern#flatternChannel(Movie movie, SeekableByteChannel out)` is never closed.

**Comment by Nirostar** [comment]
I tried it anyway. I hope it turns out nicely and works on your side too :D

**Comment by remes2000** [comment]
Any progress on this topic? I have the same problem.

**Comment by Nirostar** [comment]
This is fixed in the current master version. When do you plan releasing 0.2.6? It has been a while since 0.2.5 and it would be splendid to use maven again.
