### ISSUE TITLE
Streaming h264 nal units to mp4

### ISSUE THREAD

**Issue by backinside** [jcodec/jcodec#414]
I'd like to stream h264 nal units without transcoding to mp4, is there a way to do it? I could not find any sample or example to do this

**Comment by svitvitskiy** [comment]
Please be more specific, what is the end result? How do you get the NAL units?

**Comment by backinside** [comment]
I have RTSP stream recorded, and I want to convert to mp4 on demand
I can already decode all the frames to a BufferedImage, and encode to mp4, but I’d like to skip that, and just save the nal units directly

**Comment by svitvitskiy** [comment]
You don't need to transcode the video. You can just remux your packets into MP4, for this you will need MP4Muxer class which basically stores your NAL units into MP4 format. Is this what you are trying to do?
When you say on-demand, do you mean generating an mp4 and then streaming it OR streaming mp4 in the process of generating it? The first would be possible with MP4Muxer and is actually fairly easy to do, the latter, while still possible, is much more complicated.

**Comment by backinside** [comment]
Thanks, I've managed to generate an mp4 out of my RTP stream

`FileChannelWrapper sink = NIOUtils.writableChannel(new File("output.mp4"));
MP4Muxer muxer = MP4Muxer.createMP4MuxerToChannel(sink);
VideoCodecMeta meta = VideoCodecMeta.createSimpleVideoCodecMeta(new Size(1920, 1080), ColorSpace.YUV420);
MuxerTrack outTrack = muxer.addVideoTrack(Codec.H264, meta);
outTrack.addFrame(MP4Packet.createMP4Packet(ByteBuffer.wrap(frameData.toByteArray()), frameNo * 1001, 24000, 1001, frameNo, FrameType.UNKNOWN, null, 0, frameNo * 1001, 0));
muxer.finish();
sink.close();`

Now how could I approach streaming the same h264 stream to a browser? Does jcodec support a format, that can be

**Comment by svitvitskiy** [comment]
The best way to create a stream these days is to break up your large file into a bunch of small mp4s, then using your javascript update video tag source at the end of every chunk with a new URL.
However, you don't even have to do that. There's already an implementation of such streaming called DASH. You just create an XML descriptor file that has the pattern of your mp4 fragments, then you import DASH implementation into your page (javascript). On the server side you demux the NAL units out of the RTP stream and store them in MP4, as soon as MP4 is greater than a certain size, you finalize it and upload to a web-storage and start a new mp4. As soon as new mp4 comes up on a web server DASH client automatically picks it up.

**Comment by Peter-Nemesys** [comment]
Since my main platform is mobile at the moment, I've ended up using broadway js to play the chunks
Thanks, for the help

**Comment by backinside** [comment]
Since my main platform is mobile at the moment, I've ended up using broadway js to play the chunks
Thanks, for the help
