### ISSUE TITLE
Versions and releases - question/clarification

### ISSUE THREAD

**Issue by garethfloodgate** [jcodec/jcodec#415]
Hello

Could you please help clarify a question regarding versions and releases of this library ?

Looking at maven central:
https://mvnrepository.com/artifact/org.jcodec/jcodec

It seems that the leatest release of jcodec is 0.2.5 - June 2019

BUT

Looking at the master branch of github and cross-referencing published releases, it appears that the current codebase is 0.2.4-SNAPSHOT (I.E. 0.2.3 was the last formal release)

Can you please provide clarity on where/what latest release is good - 

i.e. should we ignore what is in maven central (or can it be updated to reflect reality) ?

Many thanks
Gareth

**Comment by svitvitskiy** [comment]
It looks like we might have forgotten to bump the development version, just did. Thanks for catching.
