### ISSUE TITLE
Picture using ColorSpace.YUV420 or YUV420J produce tiedye effect

### ISSUE THREAD

**Issue by mondain** [jcodec/jcodec#417]
When I use jcodec to write a png to verify my decoder routines, I get a tiedye effect on my image; If I pass the same yuv content to ffmpeg the image generated is as expected. Am I doing something incorrect in the snippit below?
```java
byte[] decodedYuv = // filled with contents of decodedFrame.yuv (in zip file) attachment
int width = 720, height = 480;
// XXX copy our single dim array into multi-dim array
byte[][] ydata = new byte[3][]; // 3 planes y,u,v
// copy the Y array
ydata[0] = Arrays.copyOf(decodedYuv, width * height);
int uIndex, vIndex, uvRowBytes, halfHeight, uvSize;
if (width % 2 != 0) {
    uvRowBytes = (width + 1) / 2;
} else {
    uvRowBytes = width / 2;
}
if (height % 2 != 0) {
    halfHeight = (height + 1) / 2;
} else {
    halfHeight = height / 2;
}
uvSize = uvRowBytes * halfHeight;
uIndex = width * height;
vIndex = uIndex + uvSize;
// copy the U and V arrays
ydata[1] = Arrays.copyOfRange(decodedYuv, uIndex, uIndex + uvSize);
ydata[2] = Arrays.copyOfRange(decodedYuv, vIndex, vIndex + uvSize);
Picture decodedPic = Picture.createPicture(width, height, ydata, ColorSpace.YUV420);
try {
    AWTUtil.savePicture(decodedPic, "png", new File("decodedImage.png"));
} catch (IOException e) {
}
```
![decodedImage](https://user-images.githubusercontent.com/510557/82922913-11d9ff00-9f2f-11ea-9a7c-2176a6567910.png)

[decodedFrame.zip](https://github.com/jcodec/jcodec/files/4683412/decodedFrame.zip)

**Comment by svitvitskiy** [comment]
Hi, yes, I think I know what the problem might be.

Before using the values inside jcodec you need to offset them by -128, i.e. 0 will become -128; 128  will become 0 and so on.

This is done because java doesn't support unsigned types and we wanted to still use 1 byte per pixel to store the images.

**Comment by mondain** [comment]
Thanks for the reply @svitvitskiy I'll give that a shot

**Comment by mondain** [comment]
That worked like a champ! thanks 
```java
for (int p = 0; p < 3; p++) {
    for (int s = 0; s < ydata[p].length; s++) {
        ydata[p][s] += (byte) -128;
    }
}
```
