### ISSUE TITLE
Add support for FU-A defragmentation

### ISSUE THREAD

**Issue by vidtec** [jcodec/jcodec#427]
When receiving H264 over RTP, it may be neccessary to support fragmented NALs

In order to support this, NALUnit must recognise FU-A NALs and an algorithm is required to defragment the NALs correctly.

The associated pull reqest add support for this.

**Comment by gareth-floodgate** [comment]
Hey is there any update on approval or not on this PR ?

**Comment by zhuker** [comment]
> Hey is there any update on approval or not on this PR ?

@gareth-floodgate the PR has formatting issues, otherwise ready to merge cc @vidtec
