### ISSUE TITLE
Need help to create video from 510images

### ISSUE THREAD

**Issue by jforjava1981** [jcodec/jcodec#43]
Hi,

 I have around 509 images from which i want to create a movie. All images are in sequence. But my video stops immediately after showing first aimage for a second.
I am not able to understand the parameters meaning i pass whicle adding the frame can somebody help? following is the call i am using inside a loop:

outTrack.addFrame(new MP4Packet(result, frameNo, 1, 1, frameNo, true, null, frameNo, 0));
with following assumptions:
where, frameNo starts from 0 and ends at 509.
1 - is the time in seconds i want to show once image.

**Comment by svitvitskiy** [comment]
There are no plans to support AVI at this points, however I am open to requests.
