### ISSUE TITLE
video created with only one image less than 1 sec

### ISSUE THREAD

**Issue by dhiren8391** [jcodec/jcodec#44]
How to set duration between images??
I used mp4packet function for creating video of sequencial images and set 25 as fps and 1 as duration. how can I create slide show video of images?
Here is my code:

int fps = 25;
long duration = 1;
outTrack.addFrame(new MP4Packet(result, num, fps, duration,
						num, true, null, num, 0));
num++; //frame no.

**Comment by svitvitskiy** [comment]
s/fps/timescale

If you want the video to play slowly set small timescale and large frame duration. Say timescale=1, duration=5 will show 1 frame every 5 seconds.
