### ISSUE TITLE
mp4 metadata move

### ISSUE THREAD

**Issue by backinside** [jcodec/jcodec#447]
I'm trying to play mp4 files over http, but iOS devices download the whole file, because the metadata is at the end of the mp4
Based on this (https://stackoverflow.com/questions/14946421/why-do-webkit-browsers-need-to-download-the-entire-html5-video-mp4-before-play) using the movflags faststart flags for ffmpeg solves the issue
Is there a way, to put the metadata at the beginning of the file?
I'm constructing the file from h264 packets, is there a way to update the metadata, once all the frames are processed?

**Comment by svitvitskiy** [comment]
Take a look at [org.jcodec.movtool.WebOptimize](https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/movtool/WebOptimize.java). This class will take an existing mp4 and relocate the header to the beginning.

**Comment by backinside** [comment]
Awesome, sounds like exactly, what I need, thanks :)

**Comment by backinside** [comment]
I'm constructing mp4 out of NAL units real time, is there a way to do this without copying the whole mp4?
