### ISSUE TITLE
Could I use ColorSpace ARGB?

### ISSUE THREAD

**Issue by soarteam** [jcodec/jcodec#451]
I would like to export video with Transparent, so I want to know could jcodec can use ARGB?

**Comment by svitvitskiy** [comment]
Out of all the video coding standards JCodec currently implements (that is MPEG2,H264,ProRes,JPEG,PNG) only PNG supports transparency. That said, nothing has been done in terms of specifically supporting it in the actual implementation, so you'd have to check to see if it will work and possibly fix a couple of bugs along the way.
That said, you could 'emulate' transparency channel even when it is not specifically supported. One idea would be to pack 2 h264 streams into the same mp4 container, one would be your YCbCr and the other one would be gray for transparency.

**Comment by soarteam** [comment]
I think we can use PNG in a MOV container.
for example, in ffmpeg
 `ffmpeg -r 30 -i Record_%d.png -c:v png -pix_fmt rgba out.mov`
But it must use ffmpeg as you see.
So I want to find another way to do it.
