### ISSUE TITLE
Question: How to build the samples?

### ISSUE THREAD

**Issue by neilyoung** [jcodec/jcodec#457]
...as subject says. Sorry for the stupid question

**Comment by neilyoung** [comment]
Just asking because `mvn install` in the `samples` subdir gives:

```
~/Documents/tmp/jcodec/samples $ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.jcodec:jcodec-samples >----------------------
[INFO] Building jcodec-samples 0.2.6-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.jcodec:jcodec-javase:jar:0.2.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.365 s
[INFO] Finished at: 2021-03-17T21:44:57+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jcodec-samples: Could not resolve dependencies for project org.jcodec:jcodec-samples:jar:0.2.6-SNAPSHOT: Failure to find org.jcodec:jcodec-javase:jar:0.2.6-SNAPSHOT in https://google-gson.googlecode.com/svn/mavenrepo was cached in the local repository, resolution will not be reattempted until the update interval of gson has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by neilyoung** [comment]
Same as https://github.com/jcodec/jcodec/issues/143 just 5 years later?

**Comment by neilyoung** [comment]
Well, yes it is. You've got so many tests and in the end it breaks on such a simple thing...tstststs...

![image](https://user-images.githubusercontent.com/731020/111540406-6759f380-876f-11eb-910e-73eb94d43a1c.png)

**Comment by neilyoung** [comment]
Will re-check next year, since on the other thread the fix also took a year 👍

**Comment by neilyoung** [comment]
Too bad, btw... Looking for alternatives then. Thanks

**Comment by jcodec** [comment]
So if I understand correctly you can not build jcodec-samples project. This is because jcodec-samples depends on jcodec of the same version. In order to build it you will first need to go to the main folder, and run:
`mvn clean install`
this will build and install the jcodec-<version> into your local maven repository. In this case jcodec-0.2.6
then you'll go into subfolder 'javase' and run the same
`mvn clean install`
from there. And only then you'll be able to build jcodec-samples by going to 'samples' and running
`mvn clean install`

**Comment by neilyoung** [comment]
Did exactöy like that before posting. The install of the lib was successful (thats why my remarks abou tests). Then i went ro the sample dir and tried the same.   Im on macOS BIg Sur, jdk 11. Maybe that’s why.  But don’t worry. I built me my own sample and it works.

**Comment by neilyoung** [comment]
Ah, wait. I missed the middle step

> In this case jcodec-0.2.6
then you'll go into subfolder 'javase' and run the same

Works. Thanks. Is that documented like so? Sorry, my bad.

**Comment by neilyoung** [comment]
Am I allowed to ask another question?

**Comment by neilyoung** [comment]
OK, no. Thanks

**Comment by jcodec** [comment]
sure, what was your question?

**Comment by neilyoung** [comment]
I wrote you a mail a couple of days ago. Here it is:


First of all, thanks for this great library. I had some difficulties in the beginning but now it's rolling.

I have a little question: I have a source, which emits H.264 packets. Each mostly about 2032 byte long, so absolutely not NAL aligned. On the other side I have an RTP packetiser, which expects NAL units as input.

I tried your lib with a small test app derived from the H264Mashup sample, using a file recorded directly from the source:

 	MappedByteBuffer map = NIOUtils.mapFile(new File("/Users/decades/video.h264"));
        FileOutputStream os = new FileOutputStream(new File("test.bin"));
        NALUnitWriter out = new NALUnitWriter(os.getChannel());
        ByteBuffer nus;
        int count = 0;
        while ((nus = H264Utils.nextNALUnit(map)) != null) {
            NALUnit nu = NALUnit.read(nus);
            System.out.printf(String.format("%d: NAL Type: %s, size: %d\n", ++count, nu.type.toString(), nus.limit()));
            if (nu.type == NALUnitType.SPS) {
                out.writeUnit(nu, nus);
                break;
            }
        }

I already parsed through the entire video and so far the results are consistent compared to other parsers. At least I think I would be able to build me that "H.264 NAL Splitter" I need.

I stumbled over the first SPS unit. While parsing the video with ffmpeg....

ffmpeg -i video.h264 -c copy -bsf:v trace_headers -f null - 2> NALUS.txt

... I saw, that the first SPS was shown as a 25 byte length (200 bit) unit. This is also my idea from looking at the "test.bin", which just dumped the first SPS and left:

If I'm not wrong, I see two "emulation prevention bytes" 0x03 in the packet:

<img width="691" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/731020/112199599-9e685300-8c0e-11eb-91fd-3597e92a35aa.png">


However, my "app" shows a size of 27, which would be the size _before_ eliminating the 0x03.

3: NAL Type: SPS, size: 27

And here the question: Am I correct, if I assume, that I would have to remove the 0x03 "manually" before forwarding this packet to the network? There are some sources, which say that:

https://interoperability.blob.core.windows.net/files/MS-H264PF/%5BMS-H264PF%5D.pdf

Or is it OK to leave the buffer "as is" and just prepare the RTP packets from the header and NAL information?

TIA

Kind regards

**Comment by jcodec** [comment]
So I think you are mismatching escape/un-escape. H264Utils.NextNALUnit will not unescape the NAL unit, however NALUnitWriter will escape the NAL unit. So your code will be double-escaping the NALUnits.
To correct this you would need to call H264Utils.unescapeNAL(nus), to unescape the NAL  unit 'in-place'.

**Comment by neilyoung** [comment]
OK, thanks. That was helpful. Indeed, you are right: If I compare the original feed with the resulting feed, then I also see this double escaping. This is the same packet in the original file dumped from the H.264 source:

![image](https://user-images.githubusercontent.com/731020/112267246-73651a00-8c75-11eb-8119-a778c36f44d6.png)

I tried to follow the suggestion and attempted to unescape before carving out the "nu", but this gives a ReadOnlyBufferException in the unescape function:

![image](https://user-images.githubusercontent.com/731020/112268180-db683000-8c76-11eb-9dda-12169abc5b76.png)

The exception happens here, on attempt to put back the byte to the duplicate of the input:

![image](https://user-images.githubusercontent.com/731020/112268309-0e122880-8c77-11eb-9bea-0489afc48399.png)

I'm still not quite sure, if the 0x03 escapes would need to be removed before moving the result to the packetizer.

**Comment by jcodec** [comment]
Makes sense. This is because the file is mapped as READ_ONLY.
`
    public static final MappedByteBuffer mapFile(File file) throws IOException {
        FileInputStream is = new FileInputStream(file);
        MappedByteBuffer map = is.getChannel().map(MapMode.READ_ONLY, 0, file.length());
        is.close();
        return map;
    }
`
You could either change the way the file is accessed or simply clone the buffer using 'NIOUtils.cloneBuffer(nus)'

**Comment by neilyoung** [comment]
Yepp. Works. I now get exactly the same I have received from the H.264 source, just that I'm able to split it to the required NAL units.

I think I will be able to figure out, if it is OK to forward the escape bytes to the packetizer.

Thanks
