### ISSUE TITLE
Detect mp4 video file orientation using jcodec

### ISSUE THREAD

**Issue by munnadroid** [jcodec/jcodec#49]
I want to detect video file **orientation**  in my android application.
Is there any way to achieve using this library ?

**Comment by svitvitskiy** [comment]
I believe you will need to parse H.264 SEI messages. Yes, this is possible. Could you post your test file so I can look at it?

**Comment by zhuker** [comment]
fixed in 0.2.0
https://github.com/jcodec/jcodec/pull/218

**Comment by tunjid** [comment]
@zhuker @svitvitskiy,  in the test referenced above, converting the video used in the test and parsing the SEI reveals only 1 SEI message with payload type 5 (user_data_unregistered),  with the contents:

> - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

The display orientation SEI message has payload type 47.

I may be wrong here, but the rotation appears to be in the MP4 container metadata, and not the SEI of the h264 video within.

**Comment by svitvitskiy** [comment]
@tunjid, you are correct, video orientation is stored in the mp4 track. And there are multiple ways to get this information using JCodec.
If you are working with low level atoms (boxes) you can get orientation using:
```
TrakBox trak = ...
trak.getTrackHeader().isOrientation0();
trak.getTrackHeader().isOrientation90();
trak.getTrackHeader().isOrientation180();
trak.getTrackHeader().isOrientation270();
```
or if you are working with higher level MP4 demuxer API:
```
SeekableByteChannel ch = null;
try {
  ch = NIOUtils.readableChannel(source);
  MP4Demuxer demuxer = MP4Demuxer.createMP4Demuxer(ch);
  Orientation or = demuxer.getVideoTracks().get(0).getMeta().getOrientation();
  // ...
} finally {
  NIOUtils.closeQuietly(ch);
}
```
