### ISSUE TITLE
Modules jcodec and jcodec.javase export package org.jcodec.scale to module xxx

### ISSUE THREAD

**Issue by detsikas** [jcodec/jcodec#504]
Hi,
I just started using jcodec and ran into the following error, when building my project

Modules jcodec and jcodec.javase export package org.jcodec.scale to module org.eclipse.fx.drift

The target module is actually not important.

I have to use both modules as I am working with java buffered images.

I get the error as soon as I add 
    requires jcodec.javase;
    requires jcodec;

to modue-info.java file.

I would be most grateful if you could provide some assistance.

Best regards,
Nikos

**Comment by svitvitskiy** [comment]
I believe in the older versions of java this was fine, so you would get classes from both modules mixed up, which was the idea.
It seems that this is not fine anymore. So, unless you find a better solution, I would manually move classes to org.jcodec.se.scale package in the javase module. There should only be a couple of classes anyway.

**Comment by detsikas** [comment]
Thank you for the response. I will try that.
Nikos
