### ISSUE TITLE
MP4Demuxer fails casting LeafBox to SampleEntry

### ISSUE THREAD

**Issue by fedorl** [jcodec/jcodec#52]
In MP4Demuxer.processHeader

        for (TrakBox trak : Box.findAll(moov, TrakBox.class, "trak")) {
            SampleEntry se = Box.findFirst(trak, SampleEntry.class...
            if ("tmcd".equals(se.getFourcc())) {
....

But Box.findFirst can return null. Worse, it may try to create class that is not SampleEntry but instance of other Box descendant and then it fails. 
This is an abuse of templates from the box side (masquerading unchecked class cast from the caller) and as expected fails some day as in this case. Box.findFirst creates LeafBox and everything fails. 

At least it should be surrounded with try catch and continue with remaining tracks, and not fail all over without possibility to get other tracks (which are extracted ok).

Also by current design everything is private, called directly from constructor and then calling endless statics.. Very sad creators of this otherwise great library did not put some minimal effort into design and possibility to override behavior.   Now the only quick cure for many such bugs is to copy blocks of code from the source..

**Comment by svitvitskiy** [comment]
Good point, blind casting in this case will cause error if sample entry is not known.
Could you post your test file?
Patches are always welcome btw

**Comment by svitvitskiy** [comment]
Fixed in 50ab3c3645d0b15701896ffc2651c62a3bb9c9a7
