### ISSUE TITLE
Change speed of video

### ISSUE THREAD

**Issue by benexus** [jcodec/jcodec#58]
I have an animated GIF and 3 images to create a Video
My TimeScale is 1000
I'm showing the frames for the GIF at a spedd of 100
At the end of the GIF I need to concatenate the 3 images at a speed of 200
For some reasons the last frame of the animated GIF appears for at least 1 second

Is there any issue when changing speed at the middle of the video?

**Comment by svitvitskiy** [comment]
Depends on a player. Could you post your output file and which device/sw version you are playing it on?

**Comment by zhuker** [comment]
animated gifs are not supported by jcodec
