### ISSUE TITLE
H264Encode with SequenceEncoder creates mp4 with wrong colors

### ISSUE THREAD

**Issue by rich-coe** [jcodec/jcodec#59]
I'm trying to create an mp4 with SequenceEncoder. 
The colors come out wrong in the mp4 when viewed with vlc.
I created a test case that calls ColorUtil.getTransform(ColorSpace.RGB, ColorSpace.YUV420J)
and then ColorUtil.getTransform(ColorSpace.YUV420J, ColorSpace.RGB).

On that single frame, the colors are all messed up as well. 

In RgbToYuv420j (rgb to YUV420 jpeg?), it calculates four Y values from
two adjacent rows and sums the U and V values together.  I couldn't find
anything on the web about summing the U and V values for the four pixels
together, but I might be looking in the wrong place.

RgbToYuv420p is very similar RgbToYuv420j, but allows two values as input 
to mask off the lower bits with an upShift and downShift values.

Any suggestions on how to get RGB data correctly rendered in an MP4 would
be appreciated. 

I'm using jcodec from master as of 12 Sep 2014.

**Comment by svitvitskiy** [comment]
Could you post source, result, your code and preferably sample images that demonstrate color mismatch? Thanks for reporting.

**Comment by rich-coe** [comment]
This was my issue.
When constructing the RGB data into the dataBuffer of the Raster, the pixels were being packed like so:
int elem = (pixels[ipx++] << 16) + (pixels[ipx++] << 8) + pixels[ipx++]
The issue is that each shifted byte is sign extended and causes the elem value to overflow.
The solution is to mask off the bits for each shifted byte.

**Comment by svitvitskiy** [comment]
I am wondering if you could use BitmapUtil.fromBitmap instead?

https://github.com/jcodec/jcodec/blob/master/android/android/org/jcodec/scale/BitmapUtil.java#L27
