### ISSUE TITLE
mp4 generated with jcodec won't display in flash

### ISSUE THREAD

**Issue by rich-coe** [jcodec/jcodec#61]
I'm trying to make mp4's that display in the flash player.   When the flash player loads the jcodec mp4 it displays the last frame of the movie and the progress bar advances for the length of the movie, but the movie never displays.  vlc displays the movie normally, with no errors.

I suspect the flash player might be looking for something in the mp4 header, but I haven't a clue on how to find out what it might be.

**Comment by mondain** [comment]
I've got an example project here: https://github.com/mondain/h264app which isn't jcodec specific, but it may help you understand how to "format" the data for flash

**Comment by rich-coe** [comment]
I use openh264 to create the movie and jcodec to construct the mp4 without an issue.
I researched this a bit, and the h264 decoder in flash and in windows doesn't like the simple h264 encoding produced by jcodec.

**Comment by svitvitskiy** [comment]
Ok, so in other words it 'doesn't like' CAVLC coding and it wants CABAC?

**Comment by rich-coe** [comment]
I would assume so.   It could also be something simple as well.   I did not do an exhaustive search and without source code, nearly impossible or exhausting.
