### ISSUE TITLE
How to Play h.264 byte frames in android?

### ISSUE THREAD

**Issue by srajesh529** [jcodec/jcodec#68]
i am not having the .mp4 file path,i am having byte array of .h264 format,how to convert .mp4 format and play the video?

**Comment by svitvitskiy** [comment]
I assume you want to mux your raw h.264 frames into mp4 container? In that case use MP4Muxer like in this sample:

https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/TranscodeMain.java#L1086

If you have a file (a stream) with raw h.264 bytestream (AnnexB stream) you may use MappedH264ES to parse individual frames out of it:
https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/TranscodeMain.java#L704

**Comment by svitvitskiy** [comment]
public void transcode(Cmd cmd) throws IOException {
            SeekableByteChannel sink = null;
            try {
                sink = writableFileChannel("filepath");

                MP4Muxer muxer = new MP4Muxer(sink, Brand.MP4);

                int timescale = 25;
                FramesMP4MuxerTrack outTrack = muxer.addTrack(TrackType.VIDEO, (int) timescale);

                List<ByteBuffer> spsList = new ArrayList<ByteBuffer>();
                List<ByteBuffer> ppsList = new ArrayList<ByteBuffer>();

                int frameDurationTv = 1;
                for (...) {
                    ByteBuffer h264RawFrame = ...;
                    // This removes SPS/PPS NAL units from the buffer and adds them
                    // to the lists above so they can later be stored in MP4 header
                    H264Utils.wipePS(h264RawFrame, spsList, ppsList);

                    // This is needed to know whether this is a sync frame
                    NALUnit nu = NALUnit.read(NIOUtils.from(h264RawFrame.duplicate(), 4));
                    
                    // Here we convert from AnnexB sync code (00 00 00 01) format
                    // to MP4 32bit NAL size format
                    H264Utils.encodeMOVPacket(h264RawFrame);

                    // This is the actual packet that goes into MP4 file
                    int frameNo = ...;
                    MP4Packet pkt = new MP4Packet(h264RawFrame, frameNo * frameDurationTv, timescale, frameDurationTv, frameNo, true, null, frameNo
                        * frameDurationTv, 0);
                    pkt.setKeyFrame(nu.type == NALUnitType.IDR_SLICE);
                    outTrack.addFrame(pkt);
                }
                // This addes the first SPS/PPS pair collected in the loop above to the header of this MP4
                // This code assumes that all SPS/PPS are the same
                outTrack.addSampleEntry(H264Utils.createMOVSampleEntry(spsList.subList(0, 1), ppsList.subList(0, 1), 4));

                // This stores the header and finalizing writing of an MP4 file
                muxer.writeHeader();
            } finally {
                if (sink != null)
                    sink.close();
                if (source != null)
                    source.close();
            }
        }

**Comment by skand24** [comment]
> i am not having the .mp4 file path,i am having byte array of .h264 format,how to convert .mp4 format and play the video?

Hi Have you resolved same issue , I 've same issue
