### ISSUE TITLE
Images are not capturing for MPEG4 Codec.

### ISSUE THREAD

**Issue by balajikaliappan** [jcodec/jcodec#69]
Hi,

Im trying to capture the thumbnail from Mp4 video which has MPEG4 codec. The same code is working for H264 codec but not for MPEG4 codec. Please let me know the way to capture the image for MPEG4 codec. 

Please help me guys

Thanks,
Balaji

**Comment by svitvitskiy** [comment]
If you need it to work with MPEG4 ASP (ISO/IEC 14496-2) then unfortunately this is not supported (yet). There are no plans (yet) to support this codec. However if there's a good case I can consider implementing it. Let me know.
