### ISSUE TITLE
JCodec don't include the license file

### ISSUE THREAD

**Issue by puntogil** [jcodec/jcodec#70]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by svitvitskiy** [comment]
Fixed in 2d752b0c6600c495f59a416e6c648fa8afa42da8
