### ISSUE TITLE
Optimizing encoded H264 size

### ISSUE THREAD

**Issue by atonparker** [jcodec/jcodec#72]
I'm using the `SequenceEncoder` to encode a MP4/H264 video, but the file size is pretty enormous when compared to the equivalent ffmpeg output. I'm completely green with video encoding, so I'm not sure if it is an issue with how `SequenceEncoder` is configured, or with the Baseline codec itself. Can the muxer in `SequenceEncoder` be configured to optimize for size?

**Comment by svitvitskiy** [comment]
Well, this is expected as JCodec's H.264 is rudimentary. It will produce
enormous output compared the state-of-the-art x264 encoder used in ffmpeg.

Stan

**Comment by atonparker** [comment]
OK, thanks for the quick response.
