### ISSUE TITLE
Jcodec works in DVR IP Camera  format h.264 ?

### ISSUE THREAD

**Issue by henriquem** [jcodec/jcodec#73]
Is possible get image from IP camera with format h.264 ?

Because, I  cannot make it works as example below, accessing DVR Cam by ip:

    Socket s = new Socket();
    s.connect(new InetSocketAddress("ip_cam_dvr", 6035));
    s_out = new PrintWriter(s.getOutputStream(), true);
    s_in = new BufferedReader(new InputStreamReader(s.getInputStream()));
 
until here everything is ok, works fine... it seems connect on ip and port - ok 
but it "hangs" when I try to use s_in.read()  (seems frozen in the s_in.read()):
  
    byte[] b = new byte[BUFFER_SIZE];
    int bytesRead = 0;
    System.out.println("Reading... \n");
    while((bytesRead = s_in.read()) > 0) // freezen in s_in.read()
    {
        System.out.println(s_in.readLine());
    }
    
Some suggestion ?

**Comment by svitvitskiy** [comment]
Reading your bug description it looks like you're having a problem @ network level and not the actual video-related problem.
Closing this because JCodec is purely a video/audio codec library at this point. You will have to find an appropriate library to work with IP camera network protocol.
