### ISSUE TITLE
Version 0.1.9 in Maven Central Repository does not support org.jcodec.api.FrameGrab#getFrame

### ISSUE THREAD

**Issue by combS8214808** [jcodec/jcodec#79]
I added the Gradle dependency to `org.jcodec : jcodec : 0.1.9` and tried to get a single frame from a movie using "Sample Code" in the `Readme.md`, but `org.jcodec.api.FrameGrab` didn't have method `getFrame`.
After I changed to version `0.1.5`, it worked.
Which version is the latest, and which version is required?

**Comment by svitvitskiy** [comment]
You should use the FrameGrab class from 'android' subfolder. FrameGrab in
jcodec main folder is a generic class that works both for Android and
JavaSE. Android and JavaSE have different classes for images.

Stan

**Comment by dangalg** [comment]
I can't find any android folder in 0.1.9... am I missing something?

**Comment by svitvitskiy** [comment]
git clone https://github.com/jcodec/jcodec.git
cd jcodec
cd android

But you are right, I should publish new android build to the download version of the site.

**Comment by combS8214808** [comment]
Thank you for your help.
I hope that the latest version would be published to the Maven Central soon.

**Comment by dangalg** [comment]
Great! How will we know when new version is pushed to maven central?
