### ISSUE TITLE
Could not find FrameGrab#FrameGrab(java.io.File)

### ISSUE THREAD

**Issue by combS8214808** [jcodec/jcodec#81]
I want to get a sequence of frames from a movie.
According to `Readme.md`, following code is available:

    FrameGrab grab = new FrameGrab(new File("filename.mp4"));

But I could find constructor `FrameGrab(File)` neither in `org.jcodec.api.FrameGrab`, `org.jcodec.api.android.FrameGrab` nor `org.jcodec.api.awt.FrameGrab`.  Instead of it, I could find `FrameGrab(SeekableByteChannel)`.  I couldn't how to use the class `SeekableByteChannel`.

How can I create/use `FrameGrab` class to get the frames?

**Comment by svitvitskiy** [comment]
FileChannelWrapper ch = null;
try {
    ch = NIOUtils.readableFileChannel(file);
    FrameGrab fg = new FrameGrab(ch);

    // Do your stuff here
} finally {
    NIOUtils.closeQuietly(ch);
}

**Comment by svitvitskiy** [comment]
I've corrected the README thank you for pointing out.
