### ISSUE TITLE
Google reports jcodec.org might be hacked

### ISSUE THREAD

**Issue by Robodanny** [jcodec/jcodec#82]
Google search results for jcodec include a line that says "This site may be hacked."

> JCodec - Home
> jcodec.org/
> This site may be hacked.
> Welcome to JCodec! JCodec is an open source pure java implementation of video and audio codecs and formats. Features, Roadmap. H.264 ( AVC ) Main ...

Is this a false alarm?

**Comment by svitvitskiy** [comment]
Thanks! I'll look into this.

Stan

**Comment by svitvitskiy** [comment]
I can see the message. Thanks!

**Comment by svitvitskiy** [comment]
Fixed the web-site, waiting for Google to re-evaluate
