### ISSUE TITLE
Some KeyIntervals produce artefacts or invalid movies

### ISSUE THREAD

**Issue by mrieser** [jcodec/jcodec#87]
Using `org.jcodec.samples.gen.SequenceEncoderDemo`, changing the keyInterval (`enc.getEncoder().setKeyInterval(25);`) from 25 to other values produces mixed results: A value of 12 seems to work fine. A value of 4 results in Mac OS X (10.10.4) not being able to show a preview, and QuickTime Player (10.4) not really showing any animation. A value of 3 results in no preview in Finder on OS X, and QuickTime Player showing strange artefacts but no moving ball.

**Comment by svitvitskiy** [comment]
Fixed
