### ISSUE TITLE
jcodec-javase not on Maven Central

### ISSUE THREAD

**Issue by mikera** [jcodec/jcodec#88]
The main `jcodec` artifact for version 0.1.9 can be found on Maven Central, but not `jcodec-javase`

Repo contents:
http://repo1.maven.org/maven2/org/jcodec/

I believe both artifacts should be available on Maven Central.

**Comment by svitvitskiy** [comment]
I'll make sure all relevant artifacts are in maven central for the next release (0.2)

**Comment by medloh** [comment]
Is it possible to get the Android specific jar from Maven?

I ended up just including the android src code in my Android Studio project so I could Use AndroidUtil and AWTUtil classes.  I was hoping I could just add a gradle dependency from MavenCentral for that instead.

**Comment by mikera** [comment]
Hey @svitvitskiy thanks for this great library, I made some videos using it from Clojure which you may like: https://www.youtube.com/playlist?list=PLoXP4rMxY3EoLcm3fcUbDgj3efzJg_wh7

Anyway I'm trying to share my code but people are having problems using it because jcodec-javase is not on Maven Central. Any chance of resolving this issue soon?

**Comment by zhuker** [comment]
+1

**Comment by svitvitskiy** [comment]
Releasing 0.1.9 javase to maven central. Give it a day or so to sync.

**Comment by mikera** [comment]
Awesome thanks @svitvitskiy !

**Comment by mikera** [comment]
Can confirm that this is now working fine foe me. Thanks all!
