### ISSUE TITLE
Does jcodec properly write a moov atom for MP4 files?

### ISSUE THREAD

**Issue by rdamiano** [jcodec/jcodec#89]
I have an MP4 file that I'm encoding through the same code from SequenceEncoder.java (including the call to MP4Muxer.writeHeader() at the end).

This file does successfully play in VLC and the default Android video player. However, upon trying to open the file in FFmpeg for some further modifications, it crashes with an error message of:

**Invalid data found when processing input**
**moov atom not found**

Is this something that can be modified in code?

**Unrelated:** If I understand correctly, jcodec uses the "sequence paramater set extension" for its NAL type. I was wondering if this was also something I could change via code? I'm running the MP4 generated via jcodec through another library that doesn't support this NAL type.

**Comment by svitvitskiy** [comment]
Could you attach the file and the code you use so I can look at it?

**Comment by rdamiano** [comment]
Sure, I had to strip out all unrelated code, but here's the overall idea of what I'm doing. It's split into three functions, startEncoding(), encodePixels(), and finishEncoding().

http://pastebin.com/1t5aYXFw

As for an MP4 file, here's one that generates the above message of "moov atom not found" from FFmpeg: http://fortheloss.org/misc/output.mp4

**Comment by S-Byrnes** [comment]
I actually have this very same issue and would very much like to know how I might solve this problem.

Thank you, I really need the help.

**Comment by rdamiano** [comment]
@svitvitskiy Hey, I really don't want this to come off as demanding or me rushing you, I understand that you're busy and working on this in your free time. I'm just wondering if there's any sort of ETA on this issue? I ask because I have an app update I'd like to push out that would utilize this jcodec functionality. Just wondering so I can plan my course of action, thanks!

**Comment by svitvitskiy** [comment]
Ralph, I am sorry for the delay. So I downloaded the sample from above and it play perfectly in ffplay, VLC, Quicktime X and Chrome on my Mac. I wanted to test it more but that didn't happen.

Which version of ffmpeg are you using on which platforms?

**Comment by svitvitskiy** [comment]
Also do you open the file with FFMpeg at the same time JCodec is writing it? This could explain the problem. Because the default MP4 is not made for gradual (streaming) playback. You have to have the whole file before you attempt to play it back.

Let me know

**Comment by rdamiano** [comment]
Hey @svitvitskiy, so just a few minutes ago I ended up re-trying my arrangement of running the jcodec video through ffmpeg and it seemingly works now. I've been doing a lot of code refactoring and cleaning since my original post so I'm not sure what changed but regardless this seems to have been my error. My bad, lol. Seriously don't know what was up before but all seems well now, I really appreciate you taking a look into this and sorry for wasting your time.
