### ISSUE TITLE
Android : MP4Muxer writeHeader(); outOfMemory

### ISSUE THREAD

**Issue by Math42** [jcodec/jcodec#9]
Hi,

I'm trying to create a movie from some images in an Android project.
I succeed, but with low memory device, memory dedicated is too small for writeHeader() on the MP4Muxer.

I checked the memory usage, my app is between 6MB and 11MB while adding all images to the outTrack (CompressedTrack) and then when i do writeHeader(), it goes to 26MB.

So, i doubt about it but is there another a way to do it using less memory? Or maybe with less memory leak?

I have already recycle all Android Bitmap and Jcodec Picture used after adding them to the outTrack.

And also, is it normal than produced movies doesn't works on VLC or Windows Movie Player or maybe i did something wrong?

Mathias.

    try {
            RgbToYuv420 transform = new RgbToYuv420(0, 0);

            this.ch = NIOUtils.writableFileChannel(new File(pathMovie+"out.mp4"));
            final MP4Muxer muxer = new MP4Muxer(ch, Brand.MP4);

            // Add a video track
            CompressedTrack outTrack = muxer.addTrackForCompressed(TrackType.VIDEO, 25);

            // Create H.264 encoder
            H264Encoder encoder = new H264Encoder(); // not we could use a rate control in the constructor

            // Allocate a buffer that would hold an encoded frame
            ByteBuffer _out = ByteBuffer.allocate(640 * 480 * 6); //Not sur about RGB

            // Allocate storage for SPS/PPS, they need to be stored separately in a special place of MP4 file
            ArrayList<ByteBuffer> spsList = new ArrayList<ByteBuffer>();
            ArrayList<ByteBuffer> ppsList = new ArrayList<ByteBuffer>();

            final File directory = new File(pathImage);
            final int numberOfimage = 10;
            
            num = 0;
            for (File file : directory.listFiles()) {
            	if (file.isFile()) {
	     
            		Bitmap bitmap = BitmapFactory.decodeFile(file.getPath());
            		Picture rgb = fromBitmap(bitmap);
            		bitmap.recycle();
            		
            		Picture yuv = Picture.create(rgb.getWidth(), rgb.getHeight(), ColorSpace.YUV420);
            		transform.transform(rgb, yuv);
            		
            		rgb = null;
            		
            		ByteBuffer result = encoder.encodeFrame(_out, yuv); //toEncode
            		
            		yuv = null;
            		
               	 	H264Utils.encodeMOVPacket(result, spsList, ppsList);
               	 	outTrack.addFrame(new MP4Packet(result, 0, 25, numberOfimage, num, true, null, 0, num));
               	 	outTrack.addSampleEntry(H264Utils.createMOVSampleEntry(spsList, ppsList));
               	 	
               	 	result = null;
               	 	System.gc();
	            	
	            	num++;
            	}
            }

	        // Write MP4 header and finalize recording
			muxer.writeHeader();
			
		} catch (Exception e) {
			Log.d("writer","Bonjour => "+e.toString());
		}

**Comment by sokishan4u** [comment]
i need android example of jcodec please someone mail me on 
sokishan4u@gmail.com

**Comment by quangjimy99** [comment]
Hi i use jcodec but i have a error
SequenceEncoder se = null;
			try {
				se = new SequenceEncoder(new File(
						params[0].getParentFile(), "jcodec_enc.mp4"));
					File img = new File("/mnt/sdcard/aamymap",
							"Cap1"+".PNG");
					File img2 = new File("/mnt/sdcard/aamymap",
							"Cap2"+".PNG");
					Bitmap frame = BitmapFactory.decodeFile(img
							.getAbsolutePath());
					se.encodeImage(frame);
					Bitmap frame2 = BitmapFactory.decodeFile(img2
							.getAbsolutePath());
					se.encodeImage(frame2);
				se.finish();

			} catch (IOException e) {
				Log.e(TAG, "IO", e);
			}
Line se.encodeImage(frame2); always error 
Please help me. Thank

**Comment by svitvitskiy** [comment]
Fixed in 348c3437597c4cea05532f880d3109d5ec9550aa
