### ISSUE TITLE
MP4 doesn't animate if encoded at 1fps or 2fps?

### ISSUE THREAD

**Issue by rdamiano** [jcodec/jcodec#91]
This seems sort of weird, but no matter what I do, I can't get an MP4 file produced via jcodec to properly play if it is encoded at 1fps or 2fps.

The 1fps and 2fps files only display the first frame in both VLC and Quicktime. Once the FPS is bumped up (with the same encoded frame data) it works.

I'm following the code from SequenceEncoder, here is my **FramesMP4MuxerTrack.addFrame()** function though:

    _outTrack.addFrame(new MP4Packet(result, _frameIndex, _fps, 1, _frameIndex, true, null, _frameIndex, 0));

These 1fps and 2fps files also only have the default VLC icon rather than a thumbnail image: http://i.imgur.com/1JEjHqG.png

**Comment by svitvitskiy** [comment]
All I can think of is try setting the timescale to something larger then 1. Try setting timescale to 1000, and make frame duration 1000 also. Also with new H.264 encoder not every frame is a keyframe so you might want to look at https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/api/SequenceEncoder8Bit.java#L85 for how to detect if a frame is a keyframe.

**Comment by rdamiano** [comment]
@svitvitskiy Aaand once again it looks like I jumped the gun with an issue report. It seems VLC has a history of issues with 1fps video, just like what I'm experiencing. Increasing the file cache in VLC to >1000ms fixes it. Sorry about that!
